In [2]:
import gc
from pathlib import Path

import numpy as np
import pandas as pd

import matplotlib.pyplot as plt
from matplotlib import pyplot as plt

import seaborn as sns

%matplotlib inline

In [4]:
## Import Crumblr Files ##

bg = pd.read_csv('/mnt/sdb/scz_meta_analysis_processed/dge_signatures/crumblr_outs/crumblr_broad_genotype.csv')
bgm = pd.read_csv('/mnt/sdb/scz_meta_analysis_processed/dge_signatures/crumblr_outs/crumblr_broad_genotype_matrix.csv')

x22q11 = pd.read_csv('/mnt/sdb/scz_meta_analysis_processed/dge_signatures/dreamlet_dges/disease_analyses/dream_crumblr_22q11_dge_scz_results.csv')
nrnxn1 = pd.read_csv('/mnt/sdb/scz_meta_analysis_processed/dge_signatures/dreamlet_dges/disease_analyses/dream_crumblr_NRNXN1_dge_scz_results.csv')
x3q29 = pd.read_csv('/mnt/sdb/scz_meta_analysis_processed/dge_signatures/dreamlet_dges/disease_analyses/dream_crumblr_3q29_dge_scz_results.csv')
x15q13 = pd.read_csv('/mnt/sdb/scz_meta_analysis_processed/dge_signatures/dreamlet_dges/disease_analyses/dream_crumblr_15q13_dge_scz_results.csv')
idiopathic = pd.read_csv('/mnt/sdb/scz_meta_analysis_processed/dge_signatures/dreamlet_dges/disease_analyses/dream_crumblr_Idiopathic_dge_scz_results.csv')

In [6]:
bg

,Unnamed: 0,Broad_Genotype,Chemistry,Donor,Manuscript,Protocol,Sex,Day,scale(n_counts),scale(percent_mito),Residuals
0,Astrocyte GFAP+AQP4+HOPX+,2.454587e-11,0.000000e+00,0.000000,0.000000e+00,1.552050e-01,1.308001e-02,0.510905,0.082720,0.019327,0.218763
1,Dorsal Forebrain Neuron FOXG1+EMX1+NEUROG1+,0.000000e+00,0.000000e+00,0.607801,8.235442e-09,4.802022e-09,1.426300e-08,0.029770,0.087884,0.004149,0.270396
2,GABAergic GAD1+GAD2+CALB2+,2.631513e-11,8.133245e-09,0.133815,4.227321e-09,3.794021e-01,0.000000e+00,0.191932,0.050020,0.002174,0.242657
3,Hindbrain Neurons NR2F2+PBX3+LHX1+,0.000000e+00,0.000000e+00,0.000000,0.000000e+00,0.000000e+00,0.000000e+00,0.300229,0.018200,0.000035,0.681536
4,IPC EOMES+NEUROG2+PAX6+,8.525028e-11,4.242300e-10,0.298556,0.000000e+00,2.528702e-10,0.000000e+00,0.000397,0.003200,0.001390,0.696456
5,Mesenchymal-like cells VIM+VCAN+SPARC+,4.001748e-11,1.015643e-09,0.110179,3.981576e-02,2.035054e-01,1.268264e-02,0.049050,0.001261,0.011503,0.572003
6,Mixed Neurons FGF12+GRIN2B+CAMK2B+,1.306338e-12,0.000000e+00,0.326701,2.295424e-01,3.592508e-02,7.936632e-11,0.013463,0.064781,0.017515,0.312073
7,OPC OLIG1+OLIG2+PDGFRA+,1.053576e-10,0.000000e+00,0.000000,5.253290e-10,3.827786e-01,0.000000e+00,0.037875,0.008870,0.048849,0.521627
8,Oligodendrocyte OLIG1+OLIG2+MBP+,1.049722e-10,2.280393e-10,0.109248,0.000000e+00,2.669490e-01,0.000000e+00,0.188951,0.034147,0.000126,0.400579
9,Proliferative Radial Glia SOX2+HES6+TOP2A+,5.151734e-11,0.000000e+00,0.058940,4.223938e-01,1.091287e-09,1.508767e-09,0.133085,0.008641,0.008678,0.368262
10,Radial Glia SOX2+PAX6+FABP7+,4.621888e-12,5.961849e-11,0.168504,0.000000e+00,2.328335e-01,1.772984e-03,0.538463,0.000003,0.002909,0.055515
11,Radial Glia SOX2+VIM+FABP7+,2.493997e-10,0.000000e+00,0.291501,1.149733e-08,7.002780e-02,4.684850e-10,0.018648,0.042152,0.012009,0.565662
12,Stressed Glia FTL+B2M+GLUL+,4.548548e-10,6.083368e-10,0.023967,2.734895e-01,5.183430e-09,1.881526e-11,0.018174,0.016144,0.036066,0.632159

In [8]:
bgm

,Unnamed: 0,0307_GSM4306932,0524_GSM4306931,2607_GSM8779930,2607_GSM8779931,28126_GSM7847321,28126_GSM7847322,28126_GSM7847323,2909_GSM7847331,2909_GSM7847332,...,Q1_GSM7804660,Q2_GSM7804653,Q2_GSM7804659,Q5_GSM7804655,Q5_GSM7804661,Q6_GSM7804656,Q6_GSM7804662,WTC11_GSM7847323,WTC11_GSM7847331,WTC11_GSM7847332
0,Astrocyte GFAP+AQP4+HOPX+,-4.243299,-3.594637,-1.611204,-0.260730,-1.215340,-3.024491,-2.111463,-4.186274,-2.036401,...,1.047952,-2.915360,2.045759,-2.027958,2.595691,-2.708975,2.398729,-3.008360,-2.929808,-2.934777
1,Dorsal Forebrain Neuron FOXG1+EMX1+NEUROG1+,3.964376,3.493271,4.379863,4.189734,2.069858,1.319314,0.681745,2.257858,2.041137,...,2.972427,3.655056,0.726368,3.824819,3.093690,3.243229,2.128697,4.393482,4.690407,4.769133
2,GABAergic GAD1+GAD2+CALB2+,-0.273007,0.833796,1.708574,4.273274,-1.551812,-1.925879,-1.600637,-2.576836,-3.135013,...,2.002228,-1.616077,3.744064,2.807795,3.726256,2.600282,3.819732,-3.008360,-2.929808,-2.934777
3,Hindbrain Neurons NR2F2+PBX3+LHX1+,2.891592,3.035255,2.322087,1.685181,2.340008,3.290867,3.531625,2.391588,2.310287,...,1.911734,2.870514,2.500257,2.619633,1.789416,2.875273,2.279510,1.606761,1.581052,0.200717
4,IPC EOMES+NEUROG2+PAX6+,1.163873,1.359781,1.140729,0.325604,-0.763355,-3.024491,-1.012851,0.592850,0.457723,...,2.192309,-0.517465,-0.366810,-0.392203,0.214049,-0.604841,0.105204,1.502500,2.634713,2.926009
5,Mesenchymal-like cells VIM+VCAN+SPARC+,-0.235965,-1.272249,1.052253,-5.291168,0.881801,-0.191278,-3.210075,2.427110,2.292870,...,-2.193237,1.829572,-2.234555,-1.239501,-2.901932,-0.113720,-2.217184,-0.610464,-2.929808,-1.836165
6,Mixed Neurons FGF12+GRIN2B+CAMK2B+,0.222610,-0.569346,2.283283,4.220536,0.449668,2.364581,2.883494,0.076406,0.000481,...,2.979139,-2.404534,-0.085244,-0.445549,2.314814,-1.022576,1.158354,-0.063921,-1.831195,-1.325339
7,OPC OLIG1+OLIG2+PDGFRA+,-2.633861,-1.353927,-6.284033,-5.291168,-3.161250,-1.415053,-3.210075,-0.967398,-1.400412,...,-4.247361,-4.013972,-2.614045,-4.736008,-5.099157,-4.318413,-5.436060,-3.008360,-1.831195,-1.836165
8,Oligodendrocyte OLIG1+OLIG2+MBP+,-4.243299,-5.204075,-6.284033,-5.291168,-3.161250,-3.024491,-3.210075,-4.186274,-4.233625,...,-5.856799,-4.013972,-5.178994,-4.736008,-5.099157,-4.318413,-5.436060,-3.008360,-2.929808,-2.934777
9,Proliferative Radial Glia SOX2+HES6+TOP2A+,2.450025,2.614758,2.093208,1.948047,2.505176,3.238907,3.632608,1.645609,1.486687,...,1.937612,3.987383,2.514943,3.663077,1.275868,3.239060,2.056701,3.479324,3.083908,2.842875
10,Radial Glia SOX2+PAX6+FABP7+,3.362094,3.632445,1.958987,1.822789,1.233199,1.394349,3.365001,2.114512,2.074473,...,1.353281,4.222713,0.272044,3.366578,0.280741,3.390895,0.522365,3.664938,4.020049,3.969974
11,Radial Glia SOX2+VIM+FABP7+,1.818158,2.229001,3.524319,2.960235,3.534549,4.022156,3.470779,2.399898,2.178193,...,1.757513,2.930115,2.245768,2.031335,2.908876,2.056612,2.446633,1.069178,2.301301,2.028068
12,Stressed Glia FTL+B2M+GLUL+,-4.243299,-5.204075,-6.284033,-5.291168,-3.161250,-3.024491,-3.210075,-1.989049,-2.036401,...,-5.856799,-4.013972,-3.569556,-4.736008,-5.099157,-4.318413,-3.826622,-3.008360,-2.929808,-2.934777

In [9]:
x22q11

       logFC   AveExpr         t   P.Value  adj.P.Val         B     z.std
0  -1.081220 -4.321028 -1.506152  0.138005   0.953325 -4.581712 -1.483262
1  -0.618978  2.743449 -1.473338  0.146869   0.953325 -4.578314 -1.450680
2  -1.025467 -3.691510 -1.228361  0.224962   0.953325 -4.586793 -1.213440
3   0.617177  0.962552  0.936662  0.353589   0.953325 -4.597648  0.927650
4   0.611069 -4.503049  0.858762  0.394778   0.953325 -4.601398  0.850984
5   0.317677  1.617717  0.547324  0.586511   0.953325 -4.605135  0.543899
6  -0.278557  0.184297 -0.490961  0.625490   0.953325 -4.608521 -0.488084
7  -0.212826 -0.719167 -0.431160  0.668173   0.953325 -4.614805 -0.428657
8  -0.121787  2.428376 -0.350550  0.727481   0.953325 -4.610210 -0.348478
9  -0.158021  2.307339 -0.338185  0.736519   0.953325 -4.619497 -0.336466
10  0.202556 -0.760625  0.246126  0.806659   0.953325 -4.616537  0.244738
11 -0.075676  1.258890 -0.146217  0.884406   0.958106 -4.605591 -0.145386
12  0.006830  2.492758  0.013458  0.989313   0.989313 -4.606776  0.013395