In [1]:
import os
import gc
from pathlib import Path

import numpy as np
import pandas as pd

import matplotlib.pyplot as plt
import seaborn as sns

import anndata as ad
import scanpy as sc

%matplotlib inline

In [27]:
## Read IN ##

CSV_PATH = '/mnt/sdb/scz_meta_analysis_processed/dge_signatures/dreamlet_dges/disease_analyses/'

dge_nrxn1 = pd.read_csv(Path(CSV_PATH) / 'dreamlet_nrxn1_combined.csv')
dge_22q11 = pd.read_csv(Path(CSV_PATH) / 'dreamlet_22q11_combined.csv')
dge_idiopathic = pd.read_csv(Path(CSV_PATH) / 'dreamlet_idiopathic_combined.csv')

In [23]:
# add assay ID cols #

dge_nrxn1['assay_ID'] = dge_nrxn1['assay'].astype('str') + ' | '  +  dge_nrxn1['ID'].astype('str')
dge_22q11['assay_ID'] = dge_22q11['assay'].astype('str') + ' | '  +  dge_22q11['ID'].astype('str')
dge_idiopathic['assay_ID'] = dge_idiopathic['assay'].astype('str') + ' | '  +  dge_idiopathic['ID'].astype('str')

In [ ]:
## make logFC cutoff stuff ##

# subset to statistically signficant everywhere, then import your individual files, then make the plots #

# make figures again w meta analysis ##

In [31]:
dge_nrxn1[(dge_nrxn1['p.value'] < 0.05) & (dge_nrxn1['n.studies'] == 2)]

,ID,assay,estimate,std.error,statistic,p.value,n.studies,method
44,AAK1,Dorsal Forebrain Neuron FOXG1+EMX1+NEUROG1+,-0.224651,0.109406,-2.053370,4.003670e-02,2,FE
59,AAMP,Dorsal Forebrain Neuron FOXG1+EMX1+NEUROG1+,0.246528,0.106186,2.321662,2.025116e-02,2,FE
138,ABAT,Dorsal Forebrain Neuron FOXG1+EMX1+NEUROG1+,-0.488452,0.125973,-3.877443,1.055599e-04,2,FE
165,ABCA5,Dorsal Forebrain Neuron FOXG1+EMX1+NEUROG1+,-1.081286,0.142697,-7.577508,3.522554e-14,2,FE
167,ABCA5,Mixed Neurons FGF12+GRIN2B+CAMK2B+,-0.427858,0.208397,-2.053092,4.006362e-02,2,FE
...,...,...,...,...,...,...,...,...
93520,ZNRF2,Dorsal Forebrain Neuron FOXG1+EMX1+NEUROG1+,-0.365927,0.175685,-2.082856,3.726435e-02,2,FE
93645,ZSCAN23,Radial Glia SOX2+VIM+FABP7+,-0.420272,0.181325,-2.317781,2.046124e-02,2,FE
93717,ZSWIM5,Proliferative Radial Glia SOX2+HES6+TOP2A+,-0.437129,0.209670,-2.084845,3.708334e-02,2,FE
93726,ZSWIM6,Radial Glia SOX2+PAX6+FABP7+,-0.446510,0.208814,-2.138312,3.249144e-02,2,FE
93781,ZXDB,Proliferative Radial Glia SOX2+HES6+TOP2A+,-0.415039,0.143008,-2.902220,3.705279e-03,2,FE

In [30]:
dge_nrxn1[(dge_nrxn1['p.value'] < 0.05) & (dge_nrxn1['n.studies'] == 2)]['assay'].value_counts()

assay
Dorsal Forebrain Neuron FOXG1+EMX1+NEUROG1+    1153
Proliferative Radial Glia SOX2+HES6+TOP2A+      825
Mixed Neurons FGF12+GRIN2B+CAMK2B+              619
Radial Glia SOX2+VIM+FABP7+                     490
Radial Glia SOX2+PAX6+FABP7+                    460
Hindbrain Neurons NR2F2+PBX3+LHX1+              186
Mesenchymal-like cells VIM+VCAN+SPARC+          104
GABAergic GAD1+GAD2+CALB2+                       26
Name: count, dtype: int64

In [32]:
dge_22q11[(dge_22q11['p.value'] < 0.05) & (dge_22q11['n.studies'] == 3)]['assay'].value_counts()

assay
Radial Glia SOX2+VIM+FABP7+                    2126
Dorsal Forebrain Neuron FOXG1+EMX1+NEUROG1+    1280
Hindbrain Neurons NR2F2+PBX3+LHX1+              752
Proliferative Radial Glia SOX2+HES6+TOP2A+      528
Radial Glia SOX2+PAX6+FABP7+                    166
Mixed Neurons FGF12+GRIN2B+CAMK2B+              104
Name: count, dtype: int64

In [28]:
dge_idiopathic[(dge_idiopathic['p.value'] < 0.05) & (dge_idiopathic['n.studies'] == 2)]['assay'].value_counts()

assay
Radial Glia SOX2+PAX6+FABP7+                  437
Proliferative Radial Glia SOX2+HES6+TOP2A+    263
Radial Glia SOX2+VIM+FABP7+                    42
Hindbrain Neurons NR2F2+PBX3+LHX1+             21
Name: count, dtype: int64

In [19]:
dge_idiopathic[(dge_idiopathic['p.value'] < 0.05) & (dge_idiopathic['n.studies'] == 2)]

,ID,assay,estimate,std.error,statistic,p.value,n.studies,method
66,ABCB7,Radial Glia SOX2+PAX6+FABP7+,-0.656663,0.234648,-2.798498,0.005134,2,FE
122,ABHD17B,Radial Glia SOX2+PAX6+FABP7+,-0.465031,0.231734,-2.006747,0.044777,2,FE
156,ABL1,Radial Glia SOX2+PAX6+FABP7+,0.579588,0.210670,2.751167,0.005938,2,FE
186,ACAA1,Radial Glia SOX2+PAX6+FABP7+,0.404988,0.204402,1.981334,0.047554,2,FE
206,ACADM,Radial Glia SOX2+PAX6+FABP7+,-0.512016,0.224520,-2.280490,0.022579,2,FE
...,...,...,...,...,...,...,...,...
35278,ZNF738,Radial Glia SOX2+VIM+FABP7+,0.806232,0.317003,2.543296,0.010981,2,FE
35305,ZNF766,Radial Glia SOX2+PAX6+FABP7+,-0.612344,0.213912,-2.862593,0.004202,2,FE
35347,ZNF787,Radial Glia SOX2+PAX6+FABP7+,0.468791,0.234346,2.000423,0.045455,2,FE
35438,ZNF92,Radial Glia SOX2+PAX6+FABP7+,-0.556566,0.212130,-2.623706,0.008698,2,FE
35547,ZWINT,Proliferative Radial Glia SOX2+HES6+TOP2A+,-0.437697,0.199255,-2.196670,0.028044,2,FE

In [18]:
dge_22q11[(dge_22q11['p.value'] < 0.05) & (dge_22q11['n.studies'] == 3)]

,ID,assay,estimate,std.error,statistic,p.value,n.studies,method
40,AAGAB,Dorsal Forebrain Neuron FOXG1+EMX1+NEUROG1+,0.479128,0.169637,2.824434,0.004736,3,FE
49,AAK1,Hindbrain Neurons NR2F2+PBX3+LHX1+,-0.189660,0.070663,-2.683984,0.007275,3,FE
51,AAK1,Mixed Neurons FGF12+GRIN2B+CAMK2B+,-0.392371,0.181754,-2.158805,0.030865,3,FE
52,AAK1,Proliferative Radial Glia SOX2+HES6+TOP2A+,-0.233339,0.100957,-2.311283,0.020817,3,FE
54,AAK1,Radial Glia SOX2+VIM+FABP7+,-0.475065,0.140861,-3.372583,0.000745,3,FE
...,...,...,...,...,...,...,...,...
87917,ZSWIM5,Hindbrain Neurons NR2F2+PBX3+LHX1+,-0.341274,0.148411,-2.299511,0.021476,3,FE
87926,ZSWIM6,Proliferative Radial Glia SOX2+HES6+TOP2A+,0.149501,0.062021,2.410477,0.015932,3,FE
87935,ZSWIM7,Radial Glia SOX2+PAX6+FABP7+,0.254371,0.123243,2.063982,0.039019,3,FE
87962,ZW10,Proliferative Radial Glia SOX2+HES6+TOP2A+,0.289694,0.120951,2.395132,0.016614,3,FE
88011,ZZEF1,Radial Glia SOX2+VIM+FABP7+,-0.262676,0.128932,-2.037313,0.041619,3,FE

In [12]:
dge_nrxn1[(dge_nrxn1['p.value'] < 0.05) & (dge_nrxn1['n.studies'] == 2)]

,ID,assay,estimate,std.error,statistic,p.value,n.studies,method
44,AAK1,Dorsal Forebrain Neuron FOXG1+EMX1+NEUROG1+,-0.224651,0.109406,-2.053370,4.003670e-02,2,FE
59,AAMP,Dorsal Forebrain Neuron FOXG1+EMX1+NEUROG1+,0.246528,0.106186,2.321662,2.025116e-02,2,FE
138,ABAT,Dorsal Forebrain Neuron FOXG1+EMX1+NEUROG1+,-0.488452,0.125973,-3.877443,1.055599e-04,2,FE
165,ABCA5,Dorsal Forebrain Neuron FOXG1+EMX1+NEUROG1+,-1.081286,0.142697,-7.577508,3.522554e-14,2,FE
167,ABCA5,Mixed Neurons FGF12+GRIN2B+CAMK2B+,-0.427858,0.208397,-2.053092,4.006362e-02,2,FE
...,...,...,...,...,...,...,...,...
93520,ZNRF2,Dorsal Forebrain Neuron FOXG1+EMX1+NEUROG1+,-0.365927,0.175685,-2.082856,3.726435e-02,2,FE
93645,ZSCAN23,Radial Glia SOX2+VIM+FABP7+,-0.420272,0.181325,-2.317781,2.046124e-02,2,FE
93717,ZSWIM5,Proliferative Radial Glia SOX2+HES6+TOP2A+,-0.437129,0.209670,-2.084845,3.708334e-02,2,FE
93726,ZSWIM6,Radial Glia SOX2+PAX6+FABP7+,-0.446510,0.208814,-2.138312,3.249144e-02,2,FE
93781,ZXDB,Proliferative Radial Glia SOX2+HES6+TOP2A+,-0.415039,0.143008,-2.902220,3.705279e-03,2,FE