In [1]:
import os
import gc
from pathlib import Path
from itertools import combinations

import numpy as np
import pandas as pd

import matplotlib.pyplot as plt
import seaborn as sns

import anndata as ad
import scanpy as sc

%matplotlib inline

In [2]:
## Known Genes In Deleted Regions ##

GENES_22q11 = ["TBX1",  "COMT",  "DGCR8",    "CRKL",  "PRODH",  "HIRA",  "LZTR1",    "RTN4R",   "SNAP29",    "ZDHHC8"]

GENES_22q11_EXTENDED = ["RANBP1", "MED15",  "PI4KA",  "SLC25A1", "SEPT5", "GP1BB", "ZNF74",   
                     "CLDN5",    "ARVCF", "FAM230"]

GENES_3q29 = ["DLG1", "PAK2", "FBXO45", "RNF168", "TFRC", "BDH1", "PCYT1A", "ATP13A3"]

GENES_3q29_EXTENDED = ["WDR53", "CEP19",  "TM4SF1",  "SENP5", "MFI2", "UBXN7"]

GENES_15q13 = ["CHRNA7", "OTUD7A", "KLF13", "TRPM1", "FAN1", "MTMR10", "ARHGAP11B"]

GENES_15q13_EXTNEDED = ["POLR2M", "GOLGA8A", "GOLGA8B", "GOLGA8C", "GOLGA8D", "GOLGA8E", "GOLGA8F", "GOLGA8G", "GOLGA8H", "GOLGA8I"]

In [3]:
## Read in DEG Lists ##

CSV_PATH = '/mnt/sdb/scz_meta_analysis_processed/dge_signatures/dreamlet_dges/disease_analyses/'

dge_22q11 = pd.read_csv(Path(CSV_PATH) / 'dreamlet_22q11_dge_scz_results.csv')
dge_NRXN1 = pd.read_csv(Path(CSV_PATH) / 'dreamlet_NRNXN1_dge_scz_results.csv')
dge_3q29 = pd.read_csv(Path(CSV_PATH) / 'dreamlet_3q29_dge_scz_results.csv')
dge_15q13 = pd.read_csv(Path(CSV_PATH) / 'dreamlet_15q13_dge_scz_results.csv')
dge_Idiopathic = pd.read_csv(Path(CSV_PATH) / 'dreamlet_Idiopathic_dge_scz_results.csv')

In [4]:
UNIQUE_22q11 = np.unique(dge_22q11[(dge_22q11['adj.P.Val'] < 0.05)]['ID'])

UNIQUE_NRXN1 = np.unique(dge_NRXN1[(dge_NRXN1['adj.P.Val'] < 0.05)]['ID'])

UNIQUE_3q29 = np.unique(dge_3q29[(dge_3q29['adj.P.Val'] < 0.05)]['ID'])

UNIQUE_15q13 = np.unique(dge_15q13[(dge_15q13['adj.P.Val'] < 0.05)]['ID'])

UNIQUE_Idiopathic = np.unique(dge_Idiopathic[(dge_Idiopathic['adj.P.Val'] < 0.05)]['ID'])

In [5]:
## Pairwise Combinations

gene_sets = {"22q11": set(UNIQUE_22q11), "NRXN1": set(UNIQUE_NRXN1), 
             "3q29": set(UNIQUE_3q29),    "15q13": set(UNIQUE_15q13),
             "Idiopathic": set(UNIQUE_Idiopathic),}

for (name1, set1), (name2, set2) in combinations(gene_sets.items(), 2):
    overlap = set1 & set2
    print(f"{name1} ∩ {name2}: {len(overlap)} genes")
    if len(overlap) > 0:
        print(overlap)
        print()

22q11 ∩ NRXN1: 0 genes
22q11 ∩ 3q29: 0 genes
22q11 ∩ 15q13: 0 genes
22q11 ∩ Idiopathic: 2 genes
{'PHC1', 'SSC4D'}

NRXN1 ∩ 3q29: 0 genes
NRXN1 ∩ 15q13: 0 genes
NRXN1 ∩ Idiopathic: 0 genes
3q29 ∩ 15q13: 0 genes
3q29 ∩ Idiopathic: 2 genes
{'DYNLT2B', 'FBXO45'}

15q13 ∩ Idiopathic: 0 genes

In [6]:
## What percentage of the Known Genes in the Chr Block are DE ##

## make a heatmap for this ##

## 22q11 ##

print('22q11')
print(np.unique(dge_22q11[dge_22q11['adj.P.Val'] < 0.05]['ID'][dge_22q11[dge_22q11['adj.P.Val'] < 0.05]['ID'].isin(GENES_22q11)]))
print('22q11 extended')
print(np.unique(dge_22q11[dge_22q11['adj.P.Val'] < 0.05]['ID'][dge_22q11[dge_22q11['adj.P.Val'] < 0.05]['ID'].isin(GENES_22q11_EXTENDED)]))
print('\n')

## 3q29 ##

print('3q29')
print(np.unique(dge_3q29[dge_3q29['adj.P.Val'] < 0.05]['ID'][dge_3q29[dge_3q29['adj.P.Val'] < 0.05]['ID'].isin(GENES_3q29)]))
print('3q29 extended')
print(np.unique(dge_3q29[dge_3q29['adj.P.Val'] < 0.05]['ID'][dge_3q29[dge_3q29['adj.P.Val'] < 0.05]['ID'].isin(GENES_3q29_EXTENDED)]))
print('\n')

## NRXN1 ##

print('NRXN1')
print(np.unique(dge_NRXN1[dge_NRXN1['adj.P.Val'] < 0.05]['ID'][dge_NRXN1[dge_NRXN1['adj.P.Val'] < 0.05]['ID'].isin(['NRXN1'])]))
print('\n')

## 15q13 ##

print('15q13')
print(np.unique(dge_15q13[dge_15q13['adj.P.Val'] < 0.05]['ID'][dge_15q13[dge_15q13['adj.P.Val'] < 0.05]['ID'].isin([GENES_15q13])]))
print('15q13 extended')
print(np.unique(dge_15q13[dge_15q13['adj.P.Val'] < 0.05]['ID'][dge_15q13[dge_15q13['adj.P.Val'] < 0.05]['ID'].isin([GENES_15q13_EXTNEDED])]))
print('\n')

## Idiopathic ##

print('Idiopathic')
print(np.unique(dge_Idiopathic[dge_Idiopathic['adj.P.Val'] < 0.05]['ID'][dge_Idiopathic[dge_Idiopathic['adj.P.Val'] < 0.05]['ID'].isin(GENES_22q11)]))
print(np.unique(dge_Idiopathic[dge_Idiopathic['adj.P.Val'] < 0.05]['ID'][dge_Idiopathic[dge_Idiopathic['adj.P.Val'] < 0.05]['ID'].isin(GENES_22q11_EXTENDED)]))
print(np.unique(dge_Idiopathic[dge_Idiopathic['adj.P.Val'] < 0.05]['ID'][dge_Idiopathic[dge_Idiopathic['adj.P.Val'] < 0.05]['ID'].isin(GENES_3q29)]))
print(np.unique(dge_Idiopathic[dge_Idiopathic['adj.P.Val'] < 0.05]['ID'][dge_Idiopathic[dge_Idiopathic['adj.P.Val'] < 0.05]['ID'].isin(GENES_3q29_EXTENDED)]))
print(np.unique(dge_Idiopathic[dge_Idiopathic['adj.P.Val'] < 0.05]['ID'][dge_Idiopathic[dge_Idiopathic['adj.P.Val'] < 0.05]['ID'].isin(GENES_15q13)]))
print(np.unique(dge_Idiopathic[dge_Idiopathic['adj.P.Val'] < 0.05]['ID'][dge_Idiopathic[dge_Idiopathic['adj.P.Val'] < 0.05]['ID'].isin(GENES_15q13_EXTNEDED)]))
print(np.unique(dge_Idiopathic[dge_Idiopathic['adj.P.Val'] < 0.05]['ID'][dge_Idiopathic[dge_Idiopathic['adj.P.Val'] < 0.05]['ID'].isin(['NRXN1'])]))

## Idiopathic SCZ Shares 2 genes in Common with 3q29 deletion and Nothing Else ##

22q11
['COMT' 'CRKL' 'HIRA' 'LZTR1' 'RTN4R' 'SNAP29' 'ZDHHC8']
22q11 extended
['ARVCF' 'MED15' 'PI4KA' 'RANBP1' 'SLC25A1']


3q29
['DLG1' 'FBXO45' 'PCYT1A' 'RNF168']
3q29 extended
['WDR53']


NRXN1
[]


15q13
[]
15q13 extended
[]


Idiopathic
[]
[]
['FBXO45' 'TFRC']
[]
[]
[]
[]

In [7]:
dge_22q11[(dge_22q11['adj.P.Val'] < 0.05) & (np.abs(dge_22q11['logFC']) > 1)]

,assay,ID,logFC,AveExpr,t,P.Value,adj.P.Val,B,z.std
3,Mixed Neurons FGF12+GRIN2B+CAMK2B+,DGCR6L,-1.005780,5.543906,-7.139504,6.647040e-10,0.000016,3.078634,-6.174269
30,Mesenchymal-like cells VIM+VCAN+SPARC+,C6orf47,1.059411,3.883652,5.483152,5.061716e-07,0.001607,5.938861,5.023959
34,Radial Glia SOX2+VIM+FABP7+,HIRA,-1.042272,3.166057,-5.502756,1.474575e-06,0.004144,-0.418815,-4.814651
35,Mesenchymal-like cells VIM+VCAN+SPARC+,IFI27,1.987861,3.392458,5.275109,1.515710e-06,0.004144,2.179954,4.809153
41,Radial Glia SOX2+PAX6+FABP7+,SLC25A1,-1.006556,5.840882,-5.017550,2.999994e-06,0.007030,0.486380,-4.670820
44,Radial Glia SOX2+PAX6+FABP7+,COMT,-2.124549,4.210205,-4.908568,4.015905e-06,0.008783,-0.907957,-4.610557
45,Radial Glia SOX2+VIM+FABP7+,ARVCF,-1.029302,3.941597,-6.089659,4.626996e-06,0.009900,2.785095,-4.581026
49,Mesenchymal-like cells VIM+VCAN+SPARC+,PIK3CA,-1.522734,4.096901,-5.037840,9.245791e-06,0.017921,4.222712,-4.434100
54,Radial Glia SOX2+VIM+FABP7+,COMT,-2.063470,4.120611,-4.594966,1.611281e-05,0.028833,-3.930001,-4.312898
56,Proliferative Radial Glia SOX2+HES6+TOP2A+,COMT,-2.073465,3.273161,-4.558106,1.692035e-05,0.029215,-2.852614,-4.302078
59,Mesenchymal-like cells VIM+VCAN+SPARC+,PHC1,-1.237607,4.141524,-4.713216,1.866853e-05,0.030622,2.763915,-4.280248
65,Radial Glia SOX2+VIM+FABP7+,SSC4D,1.050100,1.567539,4.439816,2.872640e-05,0.042836,-0.131626,4.183335
66,Dorsal Forebrain Neuron FOXG1+EMX1+NEUROG1+,COMT,-2.035749,3.011438,-4.546270,2.945175e-05,0.043262,-2.451204,-4.177665

In [8]:
dge_22q11[(dge_22q11['adj.P.Val'] < 0.05) & (dge_22q11['assay'] == 'Dorsal Forebrain Neuron FOXG1+EMX1+NEUROG1+')]

,assay,ID,logFC,AveExpr,t,P.Value,adj.P.Val,B,z.std
0,Dorsal Forebrain Neuron FOXG1+EMX1+NEUROG1+,PI4KA,-0.820498,4.971860,-7.643632,3.560559e-11,0.000004,10.374025,-6.621299
1,Dorsal Forebrain Neuron FOXG1+EMX1+NEUROG1+,MED15,-0.821131,4.531648,-7.388265,1.384501e-10,0.000007,6.960852,-6.417588
12,Dorsal Forebrain Neuron FOXG1+EMX1+NEUROG1+,SNAP29,-0.772316,5.014354,-6.811021,2.954268e-08,0.000224,6.188181,-5.544126
14,Dorsal Forebrain Neuron FOXG1+EMX1+NEUROG1+,CRKL,-0.796497,4.724569,-5.997730,4.843240e-08,0.000318,5.201524,-5.456972
15,Dorsal Forebrain Neuron FOXG1+EMX1+NEUROG1+,C22orf39,-0.727337,5.706293,-5.954626,6.794210e-08,0.000418,3.263112,-5.396530
20,Dorsal Forebrain Neuron FOXG1+EMX1+NEUROG1+,ESS2,-0.741827,4.140018,-5.784844,1.609722e-07,0.000754,4.854414,-5.239546
27,Dorsal Forebrain Neuron FOXG1+EMX1+NEUROG1+,RANBP1,-0.634556,7.820246,-5.553408,4.388332e-07,0.001542,2.782138,-5.051291
32,Dorsal Forebrain Neuron FOXG1+EMX1+NEUROG1+,ARVCF,-0.899626,3.588668,-5.340270,7.006262e-07,0.002090,3.825270,-4.961190
38,Dorsal Forebrain Neuron FOXG1+EMX1+NEUROG1+,DGCR2,-0.861911,3.808937,-5.091005,2.016560e-06,0.004994,2.892076,-4.751758
46,Dorsal Forebrain Neuron FOXG1+EMX1+NEUROG1+,RTN4R,-0.856013,4.226957,-4.904799,5.077799e-06,0.010633,2.310817,-4.561547
53,Dorsal Forebrain Neuron FOXG1+EMX1+NEUROG1+,DGCR6,-0.828870,3.342403,-4.694025,1.447625e-05,0.026384,1.588390,-4.336511
66,Dorsal Forebrain Neuron FOXG1+EMX1+NEUROG1+,COMT,-2.035749,3.011438,-4.546270,2.945175e-05,0.043262,-2.451204,-4.177665

In [9]:
dge_22q11[dge_22q11['adj.P.Val'] < 0.05].groupby('assay').count()

,ID,logFC,AveExpr,t,P.Value,adj.P.Val,B,z.std
assay,,,,,,,,
Dorsal Forebrain Neuron FOXG1+EMX1+NEUROG1+,12,12,12,12,12,12,12,12
Hindbrain Neurons NR2F2+PBX3+LHX1+,15,15,15,15,15,15,15,15
Mesenchymal-like cells VIM+VCAN+SPARC+,6,6,6,6,6,6,6,6
Mixed Neurons FGF12+GRIN2B+CAMK2B+,10,10,10,10,10,10,10,10
Proliferative Radial Glia SOX2+HES6+TOP2A+,10,10,10,10,10,10,10,10
Radial Glia SOX2+PAX6+FABP7+,9,9,9,9,9,9,9,9
Radial Glia SOX2+VIM+FABP7+,11,11,11,11,11,11,11,11

In [10]:
dge_NRXN1[dge_NRXN1['adj.P.Val'] < 0.05].groupby('assay').count()

Empty DataFrame
Columns: [ID, logFC, AveExpr, t, P.Value, adj.P.Val, B, z.std]
Index: []

In [11]:
dge_3q29[dge_3q29['adj.P.Val'] < 0.05].groupby('assay').count()

,ID,logFC,AveExpr,t,P.Value,adj.P.Val,B,z.std
assay,,,,,,,,
Dorsal Forebrain Neuron FOXG1+EMX1+NEUROG1+,7,7,7,7,7,7,7,7
GABAergic GAD1+GAD2+CALB2+,5,5,5,5,5,5,5,5
Hindbrain Neurons NR2F2+PBX3+LHX1+,7,7,7,7,7,7,7,7
Mixed Neurons FGF12+GRIN2B+CAMK2B+,7,7,7,7,7,7,7,7
Proliferative Radial Glia SOX2+HES6+TOP2A+,8,8,8,8,8,8,8,8
Radial Glia SOX2+PAX6+FABP7+,6,6,6,6,6,6,6,6
Radial Glia SOX2+VIM+FABP7+,11,11,11,11,11,11,11,11

In [13]:
dge_15q13[dge_15q13['adj.P.Val'] < 0.05].groupby('assay').count()

,ID,logFC,AveExpr,t,P.Value,adj.P.Val,B,z.std
assay,,,,,,,,
Dorsal Forebrain Neuron FOXG1+EMX1+NEUROG1+,3,3,3,3,3,3,3,3
GABAergic GAD1+GAD2+CALB2+,1,1,1,1,1,1,1,1
Hindbrain Neurons NR2F2+PBX3+LHX1+,1,1,1,1,1,1,1,1
Mixed Neurons FGF12+GRIN2B+CAMK2B+,1,1,1,1,1,1,1,1

In [14]:
dge_Idiopathic[dge_Idiopathic['adj.P.Val'] < 0.05].groupby('assay').count()

,ID,logFC,AveExpr,t,P.Value,adj.P.Val,B,z.std
assay,,,,,,,,
Dorsal Forebrain Neuron FOXG1+EMX1+NEUROG1+,441,441,441,441,441,441,441,441
GABAergic GAD1+GAD2+CALB2+,56,56,56,56,56,56,56,56
Hindbrain Neurons NR2F2+PBX3+LHX1+,121,121,121,121,121,121,121,121
Mesenchymal-like cells VIM+VCAN+SPARC+,147,147,147,147,147,147,147,147
Mixed Neurons FGF12+GRIN2B+CAMK2B+,34,34,34,34,34,34,34,34
Proliferative Radial Glia SOX2+HES6+TOP2A+,519,519,519,519,519,519,519,519
Radial Glia SOX2+PAX6+FABP7+,159,159,159,159,159,159,159,159
Radial Glia SOX2+VIM+FABP7+,327,327,327,327,327,327,327,327

In [15]:
## Focusing on Idiopathic SCZ ##

## To what degree are DEGs conserved across celltype ##

dge_Idiopathic[dge_Idiopathic['adj.P.Val'] < 0.05]

,assay,ID,logFC,AveExpr,t,P.Value,adj.P.Val,B,z.std
0,Proliferative Radial Glia SOX2+HES6+TOP2A+,ALAD,3.052905,2.824755,16.271148,6.344177e-21,6.243812e-16,53.005946,9.384124
1,Proliferative Radial Glia SOX2+HES6+TOP2A+,BLVRB,4.073698,5.689543,10.447764,2.266840e-16,1.115489e-11,23.195661,8.207053
2,Radial Glia SOX2+VIM+FABP7+,CERS4,3.180029,4.737593,9.621767,3.727709e-15,1.222912e-10,24.164181,7.863760
3,Proliferative Radial Glia SOX2+HES6+TOP2A+,ELOVL1,2.858966,3.220990,9.258769,4.689903e-13,1.153927e-08,18.202019,7.233995
4,Radial Glia SOX2+VIM+FABP7+,ZNF165,2.641726,1.035159,7.982792,3.805093e-12,7.489793e-08,17.282845,6.944238
...,...,...,...,...,...,...,...,...,...
1799,Proliferative Radial Glia SOX2+HES6+TOP2A+,HTATSF1,-0.823571,6.902916,-3.501434,9.113152e-04,4.980459e-02,-1.614194,-3.316565
1800,Dorsal Forebrain Neuron FOXG1+EMX1+NEUROG1+,GINM1,-1.534939,5.492069,-3.484913,9.113990e-04,4.980459e-02,-0.637860,-3.316539
1801,Radial Glia SOX2+PAX6+FABP7+,JAKMIP2,-1.782013,5.269445,-3.554382,9.125631e-04,4.984053e-02,-0.655860,-3.316182
1802,Dorsal Forebrain Neuron FOXG1+EMX1+NEUROG1+,GON4L,-1.527373,6.045581,-3.581194,9.148642e-04,4.993850e-02,-0.493868,-3.315478
1803,Proliferative Radial Glia SOX2+HES6+TOP2A+,SOX2,-0.896669,9.114642,-3.434510,9.154335e-04,4.994187e-02,-2.011146,-3.315304

In [16]:
## negative overlap and shared lists ##

## code to test difference of differences ##

In [22]:
print(dge_22q11[(dge_22q11['adj.P.Val'] < 0.05) & (dge_22q11['logFC'] > 1)]['ID'].shape)

print(dge_NRXN1[(dge_NRXN1['adj.P.Val'] < 0.05) & (dge_NRXN1['logFC'] > 1)]['ID'].shape)

print(dge_3q29[(dge_3q29['adj.P.Val'] < 0.05) & (dge_3q29['logFC'] > 1)]['ID'].shape)

print(dge_15q13[(dge_15q13['adj.P.Val'] < 0.05) & (dge_15q13['logFC'] > 1)]['ID'].shape)

print(dge_Idiopathic[(dge_Idiopathic['adj.P.Val'] < 0.05) & (dge_Idiopathic['logFC'] > 1)]['ID'].shape)

(3,)
(0,)
(6,)
(6,)
(1123,)

In [33]:
print(np.unique(dge_22q11[(dge_22q11['adj.P.Val'] < 0.05) & (dge_22q11['logFC'] > 1)]['ID']).tolist())

print(np.unique(dge_NRXN1[(dge_NRXN1['adj.P.Val'] < 0.05) & (dge_NRXN1['logFC'] > 1)]['ID'].tolist()))

print(np.unique(dge_3q29[(dge_3q29['adj.P.Val'] < 0.05) & (dge_3q29['logFC'] > 1)]['ID'].tolist()))

print(np.unique(dge_15q13[(dge_15q13['adj.P.Val'] < 0.05) & (dge_15q13['logFC'] > 1)]['ID'].tolist()))

print(np.unique(dge_Idiopathic[(dge_Idiopathic['adj.P.Val'] < 0.05) & (dge_Idiopathic['logFC'] > 1)]['ID']).tolist())

['C6orf47', 'IFI27', 'SSC4D']
[]
['CHCHD2' 'CTSF' 'ELAPOR2' 'NLRP2']
['BEX5' 'POTEI' 'TCEAL5']
['ABALON', 'ABCA7', 'ABCB10', 'ABCC10', 'ABCG4', 'ABCG8', 'ABHD14B', 'ABHD16A', 'ABHD4', 'ACAD10', 'ACADS', 'ACSL1', 'ADA', 'ADAM19', 'ADAM8', 'ADAMTS4', 'ADAMTSL4', 'ADAT2', 'ADCK1', 'ADCY7', 'ADCYAP1R1', 'ADIPOR1', 'AFAP1L2', 'AGAP4', 'AGAP6', 'AGER', 'AHCY', 'AKAP3', 'ALAD', 'ALDH16A1', 'ALDH2', 'AMACR', 'AMOT', 'ANGEL1', 'ANKDD1A', 'ANKFY1', 'ANKH', 'ANKLE1', 'ANKMY1', 'ANKRD24', 'ANKRD52', 'ANKRD9', 'ANLN', 'ANXA2R', 'ANXA4', 'AP4B1-AS1', 'AP5B1', 'APOBEC3C', 'APOC1', 'APOE', 'APOL2', 'ARFGAP1', 'ARHGEF11', 'ARHGEF17', 'ARHGEF39', 'ARHGEF40', 'ARHGEF7-AS2', 'ARID3A', 'ARL4D', 'ARL8B', 'ARMC7', 'ARMT1', 'ARNT', 'ARPC1B', 'ARRDC2', 'ASB1', 'ASH2L', 'ASIC4', 'ASNS', 'ATAD3C', 'ATF5', 'ATG14', 'ATG9A', 'ATL2', 'ATL3', 'ATOX1', 'ATP11A', 'ATP1B2', 'ATP5MGL', 'ATP6V1E1', 'ATP6V1FNB', 'ATRIP', 'ATXN7', 'AXIN1', 'AZU1', 'B3GNT2', 'B4GALT4', 'BAMBI', 'BBS9', 'BCL11B', 'BCL2L1', 'BCL2L11', 'BCL2L12', 'BEND3', 'BET1L', 'BLM', 'BLOC1S3', 'BLVRB', 'BMP2', 'BRI3BP', 'BRPF3', 'BTD', 'C15orf39', 'C16orf95-DT', 'C18orf25', 'C1GALT1', 'C1QL3', 'C1orf220', 'C1orf74', 'C2orf72', 'C2orf88', 'C6orf163', 'C7orf25', 'C8orf58', 'CA11', 'CA5B', 'CABLES2', 'CACNA1C-AS2', 'CACNB2', 'CAD', 'CAMK2D', 'CAPG', 'CAPN1', 'CAVIN1', 'CBFA2T3', 'CCDC106', 'CCDC122', 'CCDC24', 'CCNA2', 'CCNB1', 'CCND3', 'CCNDBP1', 'CD160', 'CD2AP-DT', 'CD68', 'CDC6', 'CDC7', 'CDCA5', 'CDHR1', 'CDK3', 'CDKL1', 'CDON', 'CELF4', 'CELSR1', 'CEP131', 'CEP85', 'CERCAM', 'CERNA1', 'CERS4', 'CES3', 'CFD', 'CFP', 'CGN', 'CHEK2', 'CHPT1', 'CIART', 'CINP', 'CISD3', 'CISH', 'CLDN6', 'CLN8', 'CMAS', 'CMC4', 'CNIH3', 'CNTD1', 'COL18A1', 'COL5A1', 'COL9A2', 'COLGALT1', 'COQ10B', 'COX17', 'CPNE7', 'CPOX', 'CRIM1', 'CRLF1', 'CSNK2A3', 'CSRNP1', 'CTBP1-AS', 'CTBS', 'CTF1', 'CTSV', 'CUL4A', 'CXADR', 'CXCL12', 'CYB5R1', 'CYP7B1', 'DBNDD1', 'DCAF4', 'DCST1-AS1', 'DDIAS', 'DDIT3', 'DDT', 'DEDD2', 'DEGS2', 'DESI1', 'DGKZ', 'DIP2C-AS1', 'DLC1', 'DLGAP1-AS2', 'DMGDH', 'DMKN', 'DNAAF5', 'DNAH10', 'DNAH5', 'DNAJB6', 'DNASE1L1', 'DNMBP', 'DNMT3B', 'DNPEP', 'DOCK6', 'DOK4', 'DPF3', 'DRP2', 'DUSP5', 'ECE1', 'ECHDC2', 'EDC4', 'EDEM1', 'EDEM2', 'EEF1D', 'EFNA1', 'EFNA3', 'EFNA4', 'EGFL7', 'EID3', 'EIF5A', 'ELF1', 'ELF3', 'ELFN2', 'ELK1', 'ELL2', 'ELMO3', 'ELOVL1', 'ELOVL4', 'EML2', 'ENGASE', 'ENSG00000185065', 'ENSG00000203279', 'ENSG00000204055', 'ENSG00000204758', 'ENSG00000205959', 'ENSG00000225173', 'ENSG00000225489', 'ENSG00000225554', 'ENSG00000225889', 'ENSG00000227388', 'ENSG00000227782', 'ENSG00000227908', 'ENSG00000228748', 'ENSG00000232533', 'ENSG00000232748', 'ENSG00000232995', 'ENSG00000233178', 'ENSG00000242539', 'ENSG00000242628', 'ENSG00000244701', 'ENSG00000246465', 'ENSG00000246731', 'ENSG00000250790', 'ENSG00000251143', 'ENSG00000253200', 'ENSG00000253210', 'ENSG00000253636', 'ENSG00000254528', 'ENSG00000255224', 'ENSG00000255471', 'ENSG00000257433', 'ENSG00000257764', 'ENSG00000258634', 'ENSG00000258813', 'ENSG00000258944', 'ENSG00000259529', 'ENSG00000259715', 'ENSG00000260163', 'ENSG00000260641', 'ENSG00000261071', 'ENSG00000261478', 'ENSG00000261839', 'ENSG00000261888', 'ENSG00000263823', 'ENSG00000264207', 'ENSG00000267198', 'ENSG00000267388', 'ENSG00000267397', 'ENSG00000267469', 'ENSG00000267651', 'ENSG00000267940', 'ENSG00000268220', 'ENSG00000269935', 'ENSG00000269937', 'ENSG00000269983', 'ENSG00000270074', 'ENSG00000270091', 'ENSG00000270096', 'ENSG00000270127', 'ENSG00000271344', 'ENSG00000271858', 'ENSG00000271941', 'ENSG00000272009', 'ENSG00000272077', 'ENSG00000272079', 'ENSG00000272128', 'ENSG00000272275', 'ENSG00000272356', 'ENSG00000272361', 'ENSG00000272432', 'ENSG00000272486', 'ENSG00000272512', 'ENSG00000272563', 'ENSG00000272604', 'ENSG00000272696', 'ENSG00000272744', 'ENSG00000272871', 'ENSG00000273011', 'ENSG00000273032', 'ENSG00000273084', 'ENSG00000273188', 'ENSG00000273226', 'ENSG00000273230', 'ENSG00000273237', 'ENSG00000273271', 'ENSG00000273619', 'ENSG00000274315', 'ENSG00000274341', 'ENSG00000274400', 'ENSG00000274678', 'ENSG00000274987', 'ENSG00000275055', 'ENSG00000275202', 'ENSG00000275464', 'ENSG00000275807', 'ENSG00000275812', 'ENSG00000276136', 'ENSG00000277151', 'ENSG00000277715', 'ENSG00000277938', 'ENSG00000277959', 'ENSG00000278238', 'ENSG00000278740', 'ENSG00000279080', 'ENSG00000282988', 'ENSG00000283761', 'ENSG00000284976', 'ENSG00000285444', 'ENTPD1', 'EOMES', 'EPCAM', 'EPHB4', 'EPOR', 'ERMAP', 'ESYT2', 'ETV4', 'EXOC8', 'F11R', 'F2RL1', 'FAM102A', 'FAM104A', 'FAM117A', 'FAM120C', 'FAM174B', 'FAM207A', 'FAM210B', 'FAM228A', 'FAXDC2', 'FBL', 'FBLIM1', 'FBLN2', 'FCGRT', 'FCRLB', 'FECH', 'FGFR4', 'FHL3', 'FKBP10', 'FLCN', 'FLNB', 'FLOT2', 'FLVCR1-DT', 'FN1', 'FOSL2', 'FPGT-TNNI3K', 'FRAT2', 'FRMD8', 'FTCDNL1', 'FTL', 'FUOM', 'FURIN', 'FUT3', 'FZD2', 'FZD4', 'FZD7', 'GABARAPL1', 'GABPB1', 'GABRD', 'GADD45B', 'GAL', 'GALNT8', 'GANAB', 'GDF9', 'GET4', 'GFPT1', 'GHDC', 'GID4', 'GIPC1', 'GJA1', 'GLB1L2', 'GLMP', 'GLRX5', 'GM2A', 'GMPR', 'GNAS-AS1', 'GNG10', 'GPD2', 'GPR107', 'GPR160', 'GPR19', 'GRAMD1C', 'GRB10', 'GRB14', 'GRID1', 'GRIN2C', 'GRN', 'GSTO2', 'GTF2B', 'GTF2H4', 'H2AC6', 'H2BC15', 'H2BC8', 'HADH', 'HAGHL', 'HAPLN4', 'HAS2', 'HBQ1', 'HCFC1R1', 'HCG17', 'HDDC3', 'HDHD3', 'HELZ-AS1', 'HEXIM1', 'HK1', 'HMBS', 'HMCES', 'HMOX1', 'HNRNPD-DT', 'HPRT1', 'HPS1', 'HSPG2', 'HTRA2', 'IBA57', 'IFI35', 'IFITM1', 'IGFBP3', 'IGFBP4', 'IGSF6', 'IGSF9B', 'IL10RB', 'IL11', 'IL18BP', 'IL20RB', 'IL27RA', 'IL6ST', 'INHA', 'IRAK2', 'ISCA1', 'ISG15', 'ISG20', 'ITGA2', 'ITGA5', 'ITM2A', 'ITPK1-AS1', 'ITPR1', 'JARID2', 'JOSD1', 'KAT7', 'KCNAB3', 'KCNJ9', 'KCNK12', 'KCNK6', 'KDM2B', 'KHDC3L', 'KIAA0895L', 'KIF2C', 'KIRREL1', 'KLF10', 'KLF16', 'KLHL18', 'KRI1', 'KRT18', 'KRT19', 'KRT8', 'KRTCAP3', 'KTN1-AS1', 'LAGE3', 'LAMA5', 'LAMB1', 'LARP1B', 'LASP1', 'LEFTY1', 'LEMD1-DT', 'LEPR', 'LEPROTL1', 'LGALS1', 'LGALS8', 'LGR4', 'LHFPL2', 'LIG4', 'LIN37', 'LINC00574', 'LINC01004', 'LINC01356', 'LINC01503', 'LINC01750', 'LINC01772', 'LINC02256', 'LINC02361', 'LINC02600', 'LIPT1', 'LMO2', 'LOXL1-AS1', 'LRP4-AS1', 'LRRC17', 'LTBP3', 'LXN', 'LY6G6C', 'LYPD3', 'LZTFL1', 'MADCAM1', 'MAFA', 'MAFA-AS1', 'MAL2', 'MAN2A2', 'MAN2B2', 'MAP3K1', 'MAPK15', 'MAPT-AS1', 'MARCHF2', 'MARF1', 'MASTL', 'MCC', 'MCM3AP', 'MCM6', 'MCU', 'MDC1', 'MDH1B', 'MED25', 'MED26', 'MEIOC', 'MELTF', 'MFAP3L', 'MFSD11', 'MGST2', 'MICALL2', 'MIF4GD-DT', 'MIGA2', 'MKNK1', 'MLXIPL', 'MMP24OS', 'MORC4', 'MPP1', 'MPPED2-AS1', 'MRAP2', 'MRGBP', 'MRPS25', 'MT1E', 'MT1X', 'MTURN', 'MUC3A', 'MUTYH', 'MXD4', 'MYBBP1A', 'MYC', 'MYCBP', 'MYD88', 'MYO19', 'MYO1C', 'MYORG', 'MYOZ3', 'MYPOP', 'MZT2A', 'NACC1', 'NACC2', 'NADSYN1', 'NAGA', 'NARF', 'NATD1', 'NCLN', 'NCOA4', 'NFKB2', 'NFKBIA', 'NFKBID', 'NFKBIE', 'NFYA', 'NIPA1', 'NIT2', 'NOMO2', 'NOMO3', 'NOTUM', 'NPM3', 'NPNT', 'NR1H2', 'NR1H3', 'NRBP1', 'NRTN', 'NT5DC3', 'NT5M', 'NTSR1', 'NXPH3', 'ODAD3', 'OLFML3', 'ORAI1', 'OSBP2', 'OSTF1', 'OTULIN', 'P3H2', 'PARVB', 'PAWR', 'PCBD1', 'PCCB', 'PCDH1', 'PCDHA7', 'PCDHAC2', 'PCDHB11', 'PCDHB13', 'PCDHB6', 'PCDHGA12', 'PCOLCE', 'PDCD2L', 'PDE8B', 'PDXP', 'PFDN6', 'PFKFB2', 'PGAP3', 'PGAP6', 'PGM2', 'PHC1', 'PHF13', 'PHF7', 'PIEZO1', 'PIH1D2', 'PIM1', 'PIM2', 'PINK1-AS', 'PISD', 'PKD2L2', 'PKMYT1', 'PKP2', 'PLAU', 'PLCH2', 'PLEC', 'PLEKHG3', 'PLEKHG5', 'PLEKHH3', 'PLIN3', 'PLK4', 'PLPP1', 'PLSCR1', 'PLXND1', 'PNMT', 'PNP', 'PNPLA6', 'PODXL', 'POFUT1', 'POLE', 'POLR1G', 'POLR2J3', 'POLR2L', 'POLR3G', 'PPARD', 'PPARGC1B', 'PPEF1', 'PPM1F', 'PPM1J', 'PPM1M', 'PPM1N', 'PPOX', 'PPP1R12C', 'PPP1R14A', 'PPP1R1B', 'PPP1R35', 'PPP1R3B', 'PPT2', 'PRAG1', 'PRCP', 'PRDM11', 'PRDX6', 'PRKAB1', 'PRKAB2', 'PRKAR2B', 'PRNP', 'PROCR', 'PROM2', 'PRORP', 'PRR11', 'PRR13', 'PSPN', 'PYCARD', 'PYCARD-AS1', 'RAB11FIP5', 'RAB12', 'RAB15', 'RAB36', 'RAB3IL1', 'RABGEF1', 'RAMP2-AS1', 'RAP1GAP', 'RARG', 'RASD2', 'RASGRP2', 'RASL10A', 'RASL10B', 'RASSF1-AS1', 'RASSF7', 'RAVER1', 'RBM14-RBM4', 'RCAN3', 'RESF1', 'RFESD', 'RFT1', 'RFX5', 'RGCC', 'RGS10', 'RGS3', 'RGS5', 'RHCE', 'RHOF', 'RHOG', 'RHPN2', 'RILP', 'RILPL1', 'RND1', 'RNF123', 'RNF213', 'RNF43', 'ROM1', 'ROR2', 'RP2', 'RPL12', 'RPLP1', 'RPP25', 'RPS12', 'RPS15', 'RRP8', 'RSPH1', 'RUSC1', 'S100A13', 'S100A16', 'SAP18', 'SAXO2', 'SBNO2', 'SCGB1B2P', 'SCNN1D', 'SCYL3', 'SDC1', 'SDC4', 'SDCCAG8', 'SDHAF4', 'SEC31B', 'SELENBP1', 'SEMA3F', 'SEMA4B', 'SEMA6A', 'SERINC3', 'SERINC5', 'SERPINB6', 'SERPINE2', 'SERPINH1', 'SERTAD1', 'SGMS1-AS1', 'SGPP2', 'SH3BP1', 'SH3BP2', 'SH3BP5-AS1', 'SH3PXD2A', 'SHANK1', 'SHC1', 'SIAH2', 'SIK1', 'SIN3B', 'SIPA1', 'SIPA1L2', 'SKA3', 'SKIL', 'SKP2', 'SLC19A2', 'SLC1A6', 'SLC22A23', 'SLC25A20', 'SLC25A21', 'SLC25A26', 'SLC25A37', 'SLC25A39', 'SLC26A1', 'SLC26A10', 'SLC27A2', 'SLC27A5', 'SLC29A1', 'SLC2A3', 'SLC30A10', 'SLC30A6', 'SLC36A1', 'SLC38A2', 'SLC39A14', 'SLC40A1', 'SLC43A3', 'SLC48A1', 'SLC4A5', 'SLC66A3', 'SLC7A5', 'SMAD7', 'SMAGP', 'SMARCD2', 'SMIM1', 'SMIM13', 'SMIM17', 'SMIM27', 'SMPD2', 'SMTNL2', 'SNAI1', 'SNAPC4', 'SNCA', 'SNHG8', 'SNX22', 'SOCS1', 'SOCS4', 'SOCS5', 'SORBS1', 'SORBS3', 'SOX15', 'SP1', 'SPACA6', 'SPAG5', 'SPATA6L', 'SPDYE16', 'SPEG', 'SPIN1', 'SPIN4', 'SPINT2', 'SPOUT1', 'SPP1', 'SPRING1', 'SPSB2', 'SPTAN1', 'SPTB', 'SSC4D', 'ST3GAL1', 'STARD10', 'STAT6', 'STIL', 'STIMATE', 'STK10', 'STK35', 'STK36', 'STOM', 'STON1', 'STOX1', 'STUM', 'STXBP2', 'STXBP5-AS1', 'SUN1', 'SYCP3', 'SYMPK', 'SYNGR2', 'SYNPO', 'TAF8', 'TAGLN2', 'TAMALIN', 'TANGO2', 'TAP1', 'TAS2R14', 'TBC1D1', 'TBC1D16', 'TBKBP1', 'TBRG1', 'TDRP', 'TEN1', 'TENT5B', 'TEP1', 'TEPP', 'TESMIN', 'TEX12', 'TF', 'TFAP2E-AS1', 'TFRC', 'TGFB1', 'TGFBR3', 'TGIF1', 'THEMIS2', 'THSD1', 'TIGD4', 'TIMELESS', 'TIMM8A', 'TIPARP-AS1', 'TK1', 'TLCD3A', 'TLCD4', 'TMC6', 'TMC7', 'TMEM120B', 'TMEM141', 'TMEM14C', 'TMEM185A', 'TMEM240', 'TMEM256', 'TMEM54', 'TMEM64', 'TMEM86B', 'TMEM91', 'TMTC3', 'TNFAIP8', 'TNNT1', 'TNS1', 'TONSL', 'TOP1MT', 'TPH1', 'TPST2', 'TRADD', 'TRAF7', 'TRAK2', 'TRAM2', 'TRIM14', 'TRIM21', 'TRIM25', 'TRIM45', 'TRIM47', 'TRIP10', 'TRIP13', 'TRPM4', 'TSHR', 'TTYH2', 'TUBA1C', 'TUBB6', 'TYK2', 'U2AF1L4', 'UAP1L1', 'UBAC1', 'UBE2G1', 'UBE2Q2L', 'UBE2Z', 'UBFD1', 'UBTD1', 'UCKL1', 'UCP2', 'UCP3', 'UGP2', 'ULK1', 'UNC13D', 'UPB1', 'UPP1', 'UQCR11', 'UROD', 'USP15', 'USP20', 'USP21', 'USP35', 'USP44', 'USP53', 'UTF1', 'UXT', 'VAMP8', 'VANGL1', 'VASH1-AS1', 'VASH2', 'VEGFA', 'VIL1', 'VSIG10', 'WASHC5', 'WDHD1', 'WDR81', 'WEE1', 'WIPF1', 'XK', 'XPC-AS1', 'XYLB', 'XYLT1', 'ZBED6', 'ZBTB40', 'ZC3HAV1', 'ZDHHC12', 'ZFAND2A', 'ZFYVE28', 'ZNF101', 'ZNF165', 'ZNF200', 'ZNF215', 'ZNF267', 'ZNF28', 'ZNF296', 'ZNF311', 'ZNF391', 'ZNF410', 'ZNF419', 'ZNF433', 'ZNF436', 'ZNF468', 'ZNF480', 'ZNF488', 'ZNF581', 'ZNF587B', 'ZNF592', 'ZNF594-DT', 'ZNF607', 'ZNF611', 'ZNF613', 'ZNF649', 'ZNF675', 'ZNF710-AS1', 'ZNF732', 'ZNF75D', 'ZNF761', 'ZNF843', 'ZNF845', 'ZNF888', 'ZNF90', 'ZNF93', 'ZNRD2', 'ZSCAN22', 'ZSWIM1']