In [1]:
import os
import gc
from pathlib import Path
from itertools import combinations

import numpy as np
import pandas as pd

import matplotlib.pyplot as plt
import seaborn as sns

import anndata as ad
import scanpy as sc

%matplotlib inline

/home/deepak/pixi_envs/scenic/.pixi/envs/default/lib/python3.10/site-packages/anndata/utils.py:434: FutureWarning: Importing read_csv from `anndata` is deprecated. Import anndata.io.read_csv instead.
  warnings.warn(msg, FutureWarning)
/home/deepak/pixi_envs/scenic/.pixi/envs/default/lib/python3.10/site-packages/anndata/utils.py:434: FutureWarning: Importing read_excel from `anndata` is deprecated. Import anndata.io.read_excel instead.
  warnings.warn(msg, FutureWarning)
/home/deepak/pixi_envs/scenic/.pixi/envs/default/lib/python3.10/site-packages/anndata/utils.py:434: FutureWarning: Importing read_hdf from `anndata` is deprecated. Import anndata.io.read_hdf instead.
  warnings.warn(msg, FutureWarning)
/home/deepak/pixi_envs/scenic/.pixi/envs/default/lib/python3.10/site-packages/anndata/utils.py:434: FutureWarning: Importing read_loom from `anndata` is deprecated. Import anndata.io.read_loom instead.
  warnings.warn(msg, FutureWarning)
/home/deepak/pixi_envs/scenic/.pixi/envs/default/lib/python3.10/site-packages/anndata/utils.py:434: FutureWarning: Importing read_mtx from `anndata` is deprecated. Import anndata.io.read_mtx instead.
  warnings.warn(msg, FutureWarning)
/home/deepak/pixi_envs/scenic/.pixi/envs/default/lib/python3.10/site-packages/anndata/utils.py:434: FutureWarning: Importing read_text from `anndata` is deprecated. Import anndata.io.read_text instead.
  warnings.warn(msg, FutureWarning)
/home/deepak/pixi_envs/scenic/.pixi/envs/default/lib/python3.10/site-packages/anndata/utils.py:434: FutureWarning: Importing read_umi_tools from `anndata` is deprecated. Import anndata.io.read_umi_tools instead.
  warnings.warn(msg, FutureWarning)

In [2]:
## Known Genes In Deleted Regions ##

GENES_22q11 = ["TBX1",  "COMT",  "DGCR8",    "CRKL",  "PRODH",  "HIRA",  "LZTR1",    "RTN4R",   "SNAP29",    "ZDHHC8"]

GENES_22q11_EXTENDED = ["RANBP1", "MED15",  "PI4KA",  "SLC25A1", "SEPT5", "GP1BB", "ZNF74",   
                     "CLDN5",    "ARVCF", "FAM230"]

GENES_3q29 = ["DLG1", "PAK2", "FBXO45", "RNF168", "TFRC", "BDH1", "PCYT1A", "ATP13A3"]

GENES_3q29_EXTENDED = ["WDR53", "CEP19",  "TM4SF1",  "SENP5", "MFI2", "UBXN7"]

GENES_15q13 = ["CHRNA7", "OTUD7A", "KLF13", "TRPM1", "FAN1", "MTMR10", "ARHGAP11B"]

GENES_15q13_EXTNEDED = ["POLR2M", "GOLGA8A", "GOLGA8B", "GOLGA8C", "GOLGA8D", "GOLGA8E", "GOLGA8F", "GOLGA8G", "GOLGA8H", "GOLGA8I"]

In [3]:
## Read in DEG Lists ##

CSV_PATH = '/mnt/sdb/scz_meta_analysis_processed/dge_signatures/dreamlet_dges/disease_analyses/'

dge_22q11 = pd.read_csv(Path(CSV_PATH) / 'dreamlet_22q11_dge_scz_results.csv')
dge_NRXN1 = pd.read_csv(Path(CSV_PATH) / 'dreamlet_NRNXN1_dge_scz_results.csv')
dge_3q29 = pd.read_csv(Path(CSV_PATH) / 'dreamlet_3q29_dge_scz_results.csv')
dge_15q13 = pd.read_csv(Path(CSV_PATH) / 'dreamlet_15q13_dge_scz_results.csv')
dge_Idiopathic = pd.read_csv(Path(CSV_PATH) / 'dreamlet_Idiopathic_dge_scz_results.csv')

In [4]:
UNIQUE_22q11 = np.unique(dge_22q11[(dge_22q11['adj.P.Val'] < 0.05)]['ID'])

UNIQUE_NRXN1 = np.unique(dge_NRXN1[(dge_NRXN1['adj.P.Val'] < 0.05)]['ID'])

UNIQUE_3q29 = np.unique(dge_3q29[(dge_3q29['adj.P.Val'] < 0.05)]['ID'])

UNIQUE_15q13 = np.unique(dge_15q13[(dge_15q13['adj.P.Val'] < 0.05)]['ID'])

UNIQUE_Idiopathic = np.unique(dge_Idiopathic[(dge_Idiopathic['adj.P.Val'] < 0.05)]['ID'])

In [5]:
## Pairwise Combinations

gene_sets = {"22q11": set(UNIQUE_22q11), "NRXN1": set(UNIQUE_NRXN1), 
             "3q29": set(UNIQUE_3q29),    "15q13": set(UNIQUE_15q13),
             "Idiopathic": set(UNIQUE_Idiopathic),}

for (name1, set1), (name2, set2) in combinations(gene_sets.items(), 2):
    overlap = set1 & set2
    print(f"{name1} ∩ {name2}: {len(overlap)} genes")
    if len(overlap) > 0:
        print(overlap)
        print()

22q11 ∩ NRXN1: 0 genes
22q11 ∩ 3q29: 0 genes
22q11 ∩ 15q13: 0 genes
22q11 ∩ Idiopathic: 2 genes
{'PHC1', 'SSC4D'}

NRXN1 ∩ 3q29: 0 genes
NRXN1 ∩ 15q13: 0 genes
NRXN1 ∩ Idiopathic: 0 genes
3q29 ∩ 15q13: 0 genes
3q29 ∩ Idiopathic: 1 genes
{'FBXO45'}

15q13 ∩ Idiopathic: 0 genes

In [6]:
## What percentage of the Known Genes in the Chr Block are DE ##

## make a heatmap for this ##

## 22q11 ##

print('22q11')
print(np.unique(dge_22q11[dge_22q11['adj.P.Val'] < 0.05]['ID'][dge_22q11[dge_22q11['adj.P.Val'] < 0.05]['ID'].isin(GENES_22q11)]))
print('22q11 extended')
print(np.unique(dge_22q11[dge_22q11['adj.P.Val'] < 0.05]['ID'][dge_22q11[dge_22q11['adj.P.Val'] < 0.05]['ID'].isin(GENES_22q11_EXTENDED)]))
print('\n')

## 3q29 ##

print('3q29')
print(np.unique(dge_3q29[dge_3q29['adj.P.Val'] < 0.05]['ID'][dge_3q29[dge_3q29['adj.P.Val'] < 0.05]['ID'].isin(GENES_3q29)]))
print('3q29 extended')
print(np.unique(dge_3q29[dge_3q29['adj.P.Val'] < 0.05]['ID'][dge_3q29[dge_3q29['adj.P.Val'] < 0.05]['ID'].isin(GENES_3q29_EXTENDED)]))
print('\n')

## NRXN1 ##

print('NRXN1')
print(np.unique(dge_NRXN1[dge_NRXN1['adj.P.Val'] < 0.05]['ID'][dge_NRXN1[dge_NRXN1['adj.P.Val'] < 0.05]['ID'].isin(['NRXN1'])]))
print('\n')

## 15q13 ##

print('15q13')
print(np.unique(dge_15q13[dge_15q13['adj.P.Val'] < 0.05]['ID'][dge_15q13[dge_15q13['adj.P.Val'] < 0.05]['ID'].isin([GENES_15q13])]))
print('15q13 extended')
print(np.unique(dge_15q13[dge_15q13['adj.P.Val'] < 0.05]['ID'][dge_15q13[dge_15q13['adj.P.Val'] < 0.05]['ID'].isin([GENES_15q13_EXTNEDED])]))
print('\n')

## Idiopathic ##

print('Idiopathic')
print(np.unique(dge_Idiopathic[dge_Idiopathic['adj.P.Val'] < 0.05]['ID'][dge_Idiopathic[dge_Idiopathic['adj.P.Val'] < 0.05]['ID'].isin(GENES_22q11)]))
print(np.unique(dge_Idiopathic[dge_Idiopathic['adj.P.Val'] < 0.05]['ID'][dge_Idiopathic[dge_Idiopathic['adj.P.Val'] < 0.05]['ID'].isin(GENES_22q11_EXTENDED)]))
print(np.unique(dge_Idiopathic[dge_Idiopathic['adj.P.Val'] < 0.05]['ID'][dge_Idiopathic[dge_Idiopathic['adj.P.Val'] < 0.05]['ID'].isin(GENES_3q29)]))
print(np.unique(dge_Idiopathic[dge_Idiopathic['adj.P.Val'] < 0.05]['ID'][dge_Idiopathic[dge_Idiopathic['adj.P.Val'] < 0.05]['ID'].isin(GENES_3q29_EXTENDED)]))
print(np.unique(dge_Idiopathic[dge_Idiopathic['adj.P.Val'] < 0.05]['ID'][dge_Idiopathic[dge_Idiopathic['adj.P.Val'] < 0.05]['ID'].isin(GENES_15q13)]))
print(np.unique(dge_Idiopathic[dge_Idiopathic['adj.P.Val'] < 0.05]['ID'][dge_Idiopathic[dge_Idiopathic['adj.P.Val'] < 0.05]['ID'].isin(GENES_15q13_EXTNEDED)]))
print(np.unique(dge_Idiopathic[dge_Idiopathic['adj.P.Val'] < 0.05]['ID'][dge_Idiopathic[dge_Idiopathic['adj.P.Val'] < 0.05]['ID'].isin(['NRXN1'])]))

## Idiopathic SCZ Shares 2 genes in Common with 3q29 deletion and Nothing Else ##

22q11
['COMT' 'CRKL' 'HIRA' 'LZTR1' 'RTN4R' 'SNAP29' 'ZDHHC8']
22q11 extended
['ARVCF' 'MED15' 'PI4KA' 'RANBP1' 'SLC25A1']


3q29
['DLG1' 'FBXO45' 'PCYT1A' 'RNF168']
3q29 extended
[]


NRXN1
[]


15q13
[]
15q13 extended
[]


Idiopathic
[]
[]
['FBXO45' 'TFRC']
[]
[]
[]
[]

In [7]:
dge_22q11[(dge_22q11['adj.P.Val'] < 0.05) & (np.abs(dge_22q11['logFC']) > 1)]

,assay,ID,logFC,AveExpr,t,P.Value,adj.P.Val,B,z.std
1,Mixed Neurons FGF12+GRIN2B+CAMK2B+,DGCR6L,-1.019591,5.543906,-7.256137,3.989719e-10,0.000023,3.565761,-6.254429
2,Mixed Neurons FGF12+GRIN2B+CAMK2B+,MED15,-1.002709,4.571850,-7.285524,6.377276e-10,0.000024,8.850007,-6.180812
12,Radial Glia SOX2+VIM+FABP7+,ARVCF,-1.067759,3.905471,-6.292424,2.921863e-08,0.000264,4.588398,-5.546055
24,Mesenchymal-like cells VIM+VCAN+SPARC+,C6orf47,1.048778,3.883652,5.583191,3.014912e-07,0.001401,6.321828,5.122512
30,Radial Glia SOX2+VIM+FABP7+,HIRA,-1.091463,3.156952,-5.788587,6.400092e-07,0.002430,0.877696,-4.978736
33,Mesenchymal-like cells VIM+VCAN+SPARC+,IFI27,1.996876,3.392458,5.380695,9.719776e-07,0.003364,2.424913,4.897229
34,Radial Glia SOX2+VIM+FABP7+,THY1,1.402161,3.037023,5.512177,1.038335e-06,0.003491,2.626528,4.884231
42,Radial Glia SOX2+PAX6+FABP7+,SLC25A1,-1.004481,5.840882,-5.008478,3.128498e-06,0.008562,0.488708,-4.662198
43,Radial Glia SOX2+PAX6+FABP7+,COMT,-2.127382,4.210205,-4.919259,3.844694e-06,0.010088,-0.865093,-4.619606
52,Mesenchymal-like cells VIM+VCAN+SPARC+,PIK3CA,-1.510031,4.096901,-4.998349,1.072027e-05,0.023803,4.060725,-4.402111
58,IPC EOMES+NEUROG2+PAX6+,COMT,-2.174426,4.049091,-4.593456,1.601335e-05,0.031932,-3.276991,-4.314267
59,Radial Glia SOX2+VIM+FABP7+,COMT,-2.049782,4.050111,-4.575873,1.628093e-05,0.031932,-3.341464,-4.310604
60,Proliferative Radial Glia SOX2+HES6+TOP2A+,COMT,-2.073466,3.273161,-4.560175,1.679328e-05,0.031981,-2.873307,-4.303748
61,Mesenchymal-like cells VIM+VCAN+SPARC+,PHC1,-1.243137,4.141524,-4.749671,1.711244e-05,0.031981,2.771027,-4.299577
67,Radial Glia SOX2+VIM+FABP7+,SSC4D,1.079900,1.561504,4.477938,2.565695e-05,0.044402,0.807138,4.208942

In [22]:
dge_22q11[dge_22q11['adj.P.Val'] < 0.05].groupby('assay').count()[['ID']]

                                             ID
assay
Dorsal Forebrain Neuron FOXG1+EMX1+NEUROG1+  11
Hindbrain Neurons NR2F2+PBX3+LHX1+           14
IPC EOMES+NEUROG2+PAX6+                       2
Mesenchymal-like cells VIM+VCAN+SPARC+        5
Mixed Neurons FGF12+GRIN2B+CAMK2B+            9
Proliferative Radial Glia SOX2+HES6+TOP2A+   10
Radial Glia SOX2+PAX6+FABP7+                  9
Radial Glia SOX2+VIM+FABP7+                  10

In [10]:
dge_NRXN1[dge_NRXN1['adj.P.Val'] < 0.05].groupby('assay').count()

Empty DataFrame
Columns: [ID, logFC, AveExpr, t, P.Value, adj.P.Val, B, z.std]
Index: []

In [19]:
dge_3q29[dge_3q29['adj.P.Val'] < 0.05].groupby('assay').count()[['ID']]

                                             ID
assay
Astrocyte GFAP+AQP4+HOPX+                     1
Dorsal Forebrain Neuron FOXG1+EMX1+NEUROG1+   4
GABAergic GAD1+GAD2+CALB2+                    4
Hindbrain Neurons NR2F2+PBX3+LHX1+            7
Mesenchymal-like cells VIM+VCAN+SPARC+        1
Mixed Neurons FGF12+GRIN2B+CAMK2B+            6
Oligodendrocyte OLIG1+OLIG2+MBP+              1
Proliferative Radial Glia SOX2+HES6+TOP2A+    6
Radial Glia SOX2+PAX6+FABP7+                  6
Radial Glia SOX2+VIM+FABP7+                  10

In [20]:
dge_15q13[dge_15q13['adj.P.Val'] < 0.05].groupby('assay').count()[['ID']]

                                             ID
assay
Dorsal Forebrain Neuron FOXG1+EMX1+NEUROG1+   3
GABAergic GAD1+GAD2+CALB2+                    1
Hindbrain Neurons NR2F2+PBX3+LHX1+            3
Mixed Neurons FGF12+GRIN2B+CAMK2B+            1

In [21]:
dge_Idiopathic[dge_Idiopathic['adj.P.Val'] < 0.05].groupby('assay').count()[['ID']]

                                              ID
assay
Dorsal Forebrain Neuron FOXG1+EMX1+NEUROG1+  150
GABAergic GAD1+GAD2+CALB2+                    52
Hindbrain Neurons NR2F2+PBX3+LHX1+            96
IPC EOMES+NEUROG2+PAX6+                       17
Mesenchymal-like cells VIM+VCAN+SPARC+       154
Mixed Neurons FGF12+GRIN2B+CAMK2B+            22
OPC OLIG1+OLIG2+PDGFRA+                       35
Proliferative Radial Glia SOX2+HES6+TOP2A+   447
Radial Glia SOX2+PAX6+FABP7+                 132
Radial Glia SOX2+VIM+FABP7+                  271

In [16]:
print(dge_22q11[(dge_22q11['adj.P.Val'] < 0.05) & (dge_22q11['logFC'] > 1)]['ID'].shape)

print(dge_NRXN1[(dge_NRXN1['adj.P.Val'] < 0.05) & (dge_NRXN1['logFC'] > 1)]['ID'].shape)

print(dge_3q29[(dge_3q29['adj.P.Val'] < 0.05) & (dge_3q29['logFC'] > 1)]['ID'].shape)

print(dge_15q13[(dge_15q13['adj.P.Val'] < 0.05) & (dge_15q13['logFC'] > 1)]['ID'].shape)

print(dge_Idiopathic[(dge_Idiopathic['adj.P.Val'] < 0.05) & (dge_Idiopathic['logFC'] > 1)]['ID'].shape)

(4,)
(0,)
(8,)
(7,)
(741,)

In [17]:
print(np.unique(dge_22q11[(dge_22q11['adj.P.Val'] < 0.05) & (dge_22q11['logFC'] > 1)]['ID']).tolist())

print(np.unique(dge_NRXN1[(dge_NRXN1['adj.P.Val'] < 0.05) & (dge_NRXN1['logFC'] > 1)]['ID'].tolist()))

print(np.unique(dge_3q29[(dge_3q29['adj.P.Val'] < 0.05) & (dge_3q29['logFC'] > 1)]['ID'].tolist()))

print(np.unique(dge_15q13[(dge_15q13['adj.P.Val'] < 0.05) & (dge_15q13['logFC'] > 1)]['ID'].tolist()))

print(np.unique(dge_Idiopathic[(dge_Idiopathic['adj.P.Val'] < 0.05) & (dge_Idiopathic['logFC'] > 1)]['ID']).tolist())

['C6orf47', 'IFI27', 'SSC4D', 'THY1']
[]
['CHCHD2' 'CTSF' 'ELAPOR2' 'LPAR2' 'NLRP2' 'SEM1']
['BEX5' 'POTEI' 'TCEAL5']
['ABCA7', 'ABCB10', 'ABCC10', 'ABHD14B', 'ABHD16A', 'ACADS', 'ADA', 'ADAM19', 'ADAM8', 'ADAMTS4', 'ADAMTSL4', 'ADCY7', 'ADCYAP1R1', 'ADIPOR1', 'AGAP4', 'AGAP6', 'AHCY', 'ALAD', 'ALDH16A1', 'ALDH2', 'AMACR', 'ANGEL1', 'ANKDD1A', 'ANKFY1', 'ANKH', 'ANKLE1', 'ANKMY1', 'ANKRD9', 'ANLN', 'ANXA2R', 'APOBEC3C', 'APOC1', 'APOE', 'ARHGAP8', 'ARHGEF11', 'ARID3A', 'ARL4D', 'ARL8B', 'ARMC7', 'ARMT1', 'ARPC1B', 'ASB1', 'ASH2L', 'ASIC4', 'ASNS', 'ATAD3C', 'ATF5', 'ATG14', 'ATL2', 'ATL3', 'ATOX1', 'ATP1B2', 'ATP6V1E1', 'ATP6V1FNB', 'ATRIP', 'AXIN1', 'AZU1', 'B3GNT2', 'B4GALT4', 'BAMBI', 'BCL11B', 'BCL2L1', 'BCL2L11', 'BET1L', 'BLOC1S3', 'BLVRB', 'BMP2', 'BOP1', 'BRI3BP', 'BRPF3', 'BTD', 'C15orf39', 'C18orf25', 'C1orf74', 'C2orf88', 'C6orf163', 'C8orf58', 'CABLES2', 'CAD', 'CAPN1', 'CAVIN1', 'CCDC106', 'CCDC24', 'CCDC28B', 'CCNA2', 'CCNB1', 'CCND3', 'CCNDBP1', 'CDC6', 'CDC7', 'CDCA5', 'CDH1', 'CDHR1', 'CDK3', 'CDKL1', 'CDON', 'CELF4', 'CEP131', 'CEP85', 'CERS4', 'CES3', 'CFD', 'CGN', 'CHEK2', 'CHMP2B', 'CHPT1', 'CIART', 'CINP', 'CISD3', 'CISH', 'CKS1B', 'CLDN6', 'CMAS', 'CMC4', 'CMSS1', 'COL18A1', 'COL5A1', 'COL9A2', 'COLGALT1', 'COLQ', 'COX17', 'CPNE7', 'CPOX', 'CRLF1', 'CSNK2A3', 'CTSV', 'CUL4A', 'CXCL12', 'CYB5R1', 'CYP7B1', 'DBNDD1', 'DEDD2', 'DESI1', 'DGKZ', 'DLC1', 'DMKN', 'DNAAF5', 'DNAJB6', 'DNAJC16', 'DNASE1L1', 'DNMBP', 'DNMT3B', 'DNPEP', 'DOCK6', 'DOK4', 'DPF3', 'DUSP5', 'ECE1', 'EDC4', 'EDEM1', 'EDEM2', 'EEF1D', 'EFNA1', 'EFNA4', 'EGFL7', 'EIF2S2', 'EIF5A', 'ELF1', 'ELF3', 'ELFN2', 'ELK1', 'ELL2', 'ELMO2', 'ELOVL1', 'ELOVL4', 'ENSG00000204758', 'ENSG00000227388', 'ENSG00000227782', 'ENSG00000232533', 'ENSG00000244701', 'ENSG00000246465', 'ENSG00000251143', 'ENSG00000253210', 'ENSG00000255224', 'ENSG00000255471', 'ENSG00000257433', 'ENSG00000261071', 'ENSG00000261478', 'ENSG00000263823', 'ENSG00000267198', 'ENSG00000270074', 'ENSG00000271551', 'ENSG00000272009', 'ENSG00000272077', 'ENSG00000272744', 'ENSG00000272871', 'ENSG00000273084', 'ENSG00000273271', 'ENSG00000274341', 'ENSG00000274400', 'ENSG00000275807', 'ENSG00000278238', 'ENSG00000282988', 'ENSG00000284976', 'EPCAM', 'EPHB4', 'ERMAP', 'ESYT1', 'ESYT2', 'ETV4', 'F11R', 'F2RL1', 'FAM102A', 'FAM104A', 'FAM117A', 'FAM120C', 'FAM174B', 'FAM207A', 'FAM210B', 'FAXDC2', 'FBLIM1', 'FCGRT', 'FECH', 'FGFR4', 'FHL3', 'FKBP10', 'FLCN', 'FLNB', 'FLOT2', 'FN1', 'FRAT2', 'FUOM', 'FURIN', 'FZD2', 'FZD4', 'FZD7', 'GABARAPL1', 'GADD45B', 'GANAB', 'GFPT1', 'GID4', 'GIPC1', 'GLA', 'GLB1L2', 'GLMP', 'GLRX5', 'GM2A', 'GNAS-AS1', 'GNG11', 'GPD2', 'GPR19', 'GRB10', 'GRN', 'GSTO2', 'H2AC6', 'H2BC15', 'H2BC8', 'HADH', 'HAGHL', 'HAS2', 'HBQ1', 'HCFC1R1', 'HCG17', 'HDDC3', 'HDHD3', 'HEXIM1', 'HK1', 'HMBS', 'HMOX1', 'HNRNPD-DT', 'HOPX', 'HPRT1', 'HPS1', 'HRK', 'HTRA2', 'IBA57', 'IFITM1', 'IGFBP3', 'IGFBP4', 'IGSF6', 'IL11', 'IL18BP', 'IL6ST', 'INHA', 'ITGA5', 'ITM2A', 'JARID2', 'KAT7', 'KCNA2', 'KCNAB3', 'KCNK12', 'KIAA0895L', 'KIRREL1', 'KLF10', 'KLF11', 'KLF16', 'KLHL18', 'KRT18', 'KRT8', 'KRTCAP3', 'KTN1-AS1', 'LAMA5', 'LAMB1', 'LARP1B', 'LASP1', 'LEMD1-DT', 'LEPR', 'LGALS1', 'LGALS8', 'LGMN', 'LGR4', 'LHFPL2', 'LIG4', 'LIN37', 'LINC00574', 'LINC01356', 'LINC01772', 'LINC02256', 'LINC02361', 'LIPT1', 'LMO2', 'LOXL1-AS1', 'LRRC14', 'LRRC17', 'LTBP3', 'LXN', 'LYPD3', 'MADCAM1', 'MAFA-AS1', 'MAL2', 'MAN2A2', 'MAN2B2', 'MAP3K1', 'MARCHF2', 'MARCHF3', 'MASTL', 'MCF2L-AS1', 'MCM3AP', 'MCU', 'MDC1', 'MDH1B', 'MED25', 'MEPCE', 'MFAP3L', 'MGST2', 'MICALL2', 'MIGA2', 'MIR4435-2HG', 'MKNK1', 'MLH1', 'MPP1', 'MRGBP', 'MRPL12', 'MRPS25', 'MSI1', 'MT1G', 'MT1X', 'MTURN', 'MUC1', 'MXD4', 'MYBBP1A', 'MYCBP', 'MYO1C', 'MZT2A', 'NACC1', 'NACC2', 'NADSYN1', 'NAGA', 'NARF', 'NATD1', 'NCLN', 'NEBL-AS1', 'NFATC1', 'NFKBID', 'NFKBIE', 'NFYA', 'NIPA1', 'NIT2', 'NOMO3', 'NPTN', 'NR1H2', 'NR1H3', 'NRBP1', 'NRTN', 'NT5M', 'NTSR1', 'ODAD3', 'ORAI1', 'OSBP2', 'OSTF1', 'OTULIN', 'P3H2', 'PARVB', 'PAWR', 'PCBD1', 'PCCB', 'PCDHAC2', 'PCDHB13', 'PCGF5', 'PCOLCE', 'PDCD2L', 'PDXP', 'PFKFB2', 'PGAP6', 'PHC1', 'PHF7', 'PIEZO1', 'PIM1', 'PIM2', 'PINK1-AS', 'PINX1', 'PISD', 'PKP2', 'PLAU', 'PLCH2', 'PLEKHG3', 'PLEKHG5', 'PLEKHH3', 'PLK4', 'PLPP1', 'PLSCR1', 'PLXND1', 'PNMT', 'PNP', 'PNPLA4', 'PODXL', 'POFUT1', 'POLR1G', 'POLR2L', 'POLR3G', 'PPARD', 'PPARGC1B', 'PPM1F', 'PPM1N', 'PPOX', 'PPP1R12C', 'PPP1R14A', 'PPP1R1B', 'PPP1R35', 'PPP1R3B', 'PRAG1', 'PRCP', 'PRDM11', 'PRDX6', 'PRKAB2', 'PRKAR2B', 'PROCR', 'PROM2', 'PRR13', 'PSPN', 'PYCARD', 'RAB12', 'RAB15', 'RAB36', 'RAB3IL1', 'RABGEF1', 'RAP1GAP', 'RARG', 'RASL10A', 'RASL10B', 'RASSF7', 'RESF1', 'RFESD', 'RFX5', 'RGS10', 'RGS3', 'RGS5', 'RHCE', 'RHOF', 'RHOG', 'RHPN2', 'RILP', 'RILPL1', 'RND1', 'RNF123', 'RNF139-AS1', 'RNF181', 'RNF213', 'RNF43', 'ROMO1', 'RPL12', 'RPLP1', 'RPP25', 'RPS12', 'RPS15', 'RRP8', 'RUSC1', 'S100A13', 'SAP18', 'SBNO2', 'SCGB1B2P', 'SCYL3', 'SDC1', 'SDC4', 'SDHAF4', 'SELENBP1', 'SELENOW', 'SEMA4B', 'SERINC3', 'SERINC5', 'SERPINE2', 'SERPINH1', 'SERTAD1', 'SEZ6L', 'SGMS1-AS1', 'SH3BP1', 'SH3BP2', 'SH3BP5-AS1', 'SH3PXD2A', 'SHC1', 'SIN3B', 'SIPA1', 'SIPA1L2', 'SIRT1', 'SLC1A6', 'SLC22A23', 'SLC25A26', 'SLC25A37', 'SLC25A39', 'SLC26A1', 'SLC26A10', 'SLC27A5', 'SLC2A3', 'SLC30A10', 'SLC36A1', 'SLC39A14', 'SLC43A3', 'SLC48A1', 'SLC7A5', 'SMAD7', 'SMAGP', 'SMARCD2', 'SMIM1', 'SMIM13', 'SMIM27', 'SMPD2', 'SMTNL2', 'SNAI1', 'SNCA', 'SNHG8', 'SNX22', 'SOCS1', 'SOCS4', 'SOCS5', 'SORBS1', 'SORBS3', 'SOX15', 'SP1', 'SPACA6', 'SPAG5', 'SPEG', 'SPIN4', 'SPOUT1', 'SPP1', 'SPRING1', 'SPSB2', 'SPTAN1', 'SRSF1', 'SSC4D', 'STIMATE', 'STK10', 'STK35', 'STK36', 'STOM', 'STON1', 'STOX1', 'STUM', 'STXBP2', 'SUN1', 'SYMPK', 'SYNGR2', 'SYNPO', 'TAGLN2', 'TAMALIN', 'TANGO2', 'TBC1D1', 'TBC1D16', 'TBRG1', 'TDRP', 'TEP1', 'TERF1', 'TFR2', 'TFRC', 'TGFB1', 'TGFBR3', 'TGIF1', 'THEMIS2', 'THSD1', 'TIMELESS', 'TIMM8A', 'TLCD3A', 'TLCD4', 'TMC6', 'TMC7', 'TMEM120B', 'TMEM141', 'TMEM14C', 'TMEM185A', 'TMEM240', 'TMEM256', 'TMEM64', 'TMEM91', 'TMTC3', 'TNFAIP8', 'TNNT1', 'TOB1', 'TONSL', 'TOP1MT', 'TPM2', 'TPST2', 'TRADD', 'TRAK2', 'TRIB1', 'TRIM28', 'TRIM45', 'TRIP10', 'TTYH2', 'TTYH3', 'TYK2', 'UBAC1', 'UBE2G1', 'UBE2Z', 'UBFD1', 'UBTD1', 'UCKL1', 'UCP2', 'UCP3', 'UGP2', 'ULK1', 'UNC13D', 'UNKL', 'UPP1', 'UQCR11', 'UROD', 'USP15', 'USP20', 'USP53', 'UTF1', 'VAMP8', 'VANGL1', 'VASH2', 'VEGFA', 'VIL1', 'VPS37C', 'VSIG10', 'VWA1', 'WASHC5', 'WDHD1', 'WDR5', 'WDR77', 'WDR81', 'WIPF1', 'XYLT1', 'ZBTB40', 'ZC3HAV1', 'ZDHHC12', 'ZFAND2A', 'ZNF101', 'ZNF165', 'ZNF200', 'ZNF267', 'ZNF296', 'ZNF391', 'ZNF396', 'ZNF419', 'ZNF433', 'ZNF436', 'ZNF468', 'ZNF480', 'ZNF581', 'ZNF607', 'ZNF611', 'ZNF613', 'ZNF675', 'ZNF710-AS1', 'ZNF75D', 'ZNF761', 'ZNF813', 'ZNF836', 'ZNF845', 'ZNF888', 'ZNF90', 'ZNRD2', 'ZSCAN22', 'ZSWIM1']