In [1]:
import os
import gc
from pathlib import Path

import numpy as np
import pandas as pd

import matplotlib.pyplot as plt
import seaborn as sns

import anndata as ad
import scanpy as sc

%matplotlib inline

/home/deepak/pixi_envs/scenic/.pixi/envs/default/lib/python3.10/site-packages/anndata/utils.py:434: FutureWarning: Importing read_csv from `anndata` is deprecated. Import anndata.io.read_csv instead.
  warnings.warn(msg, FutureWarning)
/home/deepak/pixi_envs/scenic/.pixi/envs/default/lib/python3.10/site-packages/anndata/utils.py:434: FutureWarning: Importing read_excel from `anndata` is deprecated. Import anndata.io.read_excel instead.
  warnings.warn(msg, FutureWarning)
/home/deepak/pixi_envs/scenic/.pixi/envs/default/lib/python3.10/site-packages/anndata/utils.py:434: FutureWarning: Importing read_hdf from `anndata` is deprecated. Import anndata.io.read_hdf instead.
  warnings.warn(msg, FutureWarning)
/home/deepak/pixi_envs/scenic/.pixi/envs/default/lib/python3.10/site-packages/anndata/utils.py:434: FutureWarning: Importing read_loom from `anndata` is deprecated. Import anndata.io.read_loom instead.
  warnings.warn(msg, FutureWarning)
/home/deepak/pixi_envs/scenic/.pixi/envs/default/lib/python3.10/site-packages/anndata/utils.py:434: FutureWarning: Importing read_mtx from `anndata` is deprecated. Import anndata.io.read_mtx instead.
  warnings.warn(msg, FutureWarning)
/home/deepak/pixi_envs/scenic/.pixi/envs/default/lib/python3.10/site-packages/anndata/utils.py:434: FutureWarning: Importing read_text from `anndata` is deprecated. Import anndata.io.read_text instead.
  warnings.warn(msg, FutureWarning)
/home/deepak/pixi_envs/scenic/.pixi/envs/default/lib/python3.10/site-packages/anndata/utils.py:434: FutureWarning: Importing read_umi_tools from `anndata` is deprecated. Import anndata.io.read_umi_tools instead.
  warnings.warn(msg, FutureWarning)

In [2]:
## Read IN ##

CSV_PATH = '/mnt/sdb/scz_meta_analysis_processed/dge_signatures/dreamlet_dges/disease_analyses/'

dge_nrxn1 = pd.read_csv(Path(CSV_PATH) / 'dreamlet_nrxn1_combined.csv')
dge_22q11 = pd.read_csv(Path(CSV_PATH) / 'dreamlet_22q11_combined.csv')
dge_idiopathic = pd.read_csv(Path(CSV_PATH) / 'dreamlet_idiopathic_combined.csv')

In [3]:
# add assay ID cols #

dge_nrxn1['assay_ID'] = dge_nrxn1['assay'].astype('str') + ' | '  +  dge_nrxn1['ID'].astype('str')
dge_22q11['assay_ID'] = dge_22q11['assay'].astype('str') + ' | '  +  dge_22q11['ID'].astype('str')
dge_idiopathic['assay_ID'] = dge_idiopathic['assay'].astype('str') + ' | '  +  dge_idiopathic['ID'].astype('str')

In [4]:
## make logFC cutoff stuff ##

# subset to statistically signficant everywhere, then import your individual files, then make the plots #

# make figures again w meta analysis ##

In [5]:
dge_nrxn1[(dge_nrxn1['p.value'] < 0.05) & (dge_nrxn1['n.studies'] == 2)]

,ID,assay,estimate,std.error,statistic,p.value,n.studies,method,assay_ID
4,A1BG,IPC EOMES+NEUROG2+PAX6+,0.436317,0.185689,2.349718,0.018788,2,FE,IPC EOMES+NEUROG2+PAX6+ | A1BG
24,AAAS,Mixed Neurons FGF12+GRIN2B+CAMK2B+,0.194898,0.093015,2.095352,0.036140,2,FE,Mixed Neurons FGF12+GRIN2B+CAMK2B+ | AAAS
49,AAK1,Dorsal Forebrain Neuron FOXG1+EMX1+NEUROG1+,-0.250432,0.107790,-2.323336,0.020161,2,FE,Dorsal Forebrain Neuron FOXG1+EMX1+NEUROG1+ | ...
59,AAMDC,Dorsal Forebrain Neuron FOXG1+EMX1+NEUROG1+,0.367891,0.156717,2.347487,0.018901,2,FE,Dorsal Forebrain Neuron FOXG1+EMX1+NEUROG1+ | ...
68,AAMP,Dorsal Forebrain Neuron FOXG1+EMX1+NEUROG1+,0.278347,0.108563,2.563917,0.010350,2,FE,Dorsal Forebrain Neuron FOXG1+EMX1+NEUROG1+ | ...
...,...,...,...,...,...,...,...,...,...
106438,ZSCAN23,Radial Glia SOX2+VIM+FABP7+,-0.535142,0.181888,-2.942149,0.003259,2,FE,Radial Glia SOX2+VIM+FABP7+ | ZSCAN23
106517,ZSWIM5,Proliferative Radial Glia SOX2+HES6+TOP2A+,-0.427385,0.210371,-2.031578,0.042196,2,FE,Proliferative Radial Glia SOX2+HES6+TOP2A+ | Z...
106534,ZSWIM7,IPC EOMES+NEUROG2+PAX6+,0.607721,0.229183,2.651684,0.008009,2,FE,IPC EOMES+NEUROG2+PAX6+ | ZSWIM7
106540,ZSWIM8,Dorsal Forebrain Neuron FOXG1+EMX1+NEUROG1+,0.315091,0.095828,3.288070,0.001009,2,FE,Dorsal Forebrain Neuron FOXG1+EMX1+NEUROG1+ | ...
106588,ZXDB,Proliferative Radial Glia SOX2+HES6+TOP2A+,-0.330291,0.152140,-2.170970,0.029933,2,FE,Proliferative Radial Glia SOX2+HES6+TOP2A+ | ZXDB

In [6]:
dge_nrxn1[(dge_nrxn1['p.value'] < 0.05) & (dge_nrxn1['n.studies'] == 2)]['assay'].value_counts()

assay
Dorsal Forebrain Neuron FOXG1+EMX1+NEUROG1+    1339
Proliferative Radial Glia SOX2+HES6+TOP2A+      789
Mixed Neurons FGF12+GRIN2B+CAMK2B+              742
IPC EOMES+NEUROG2+PAX6+                         627
Astrocyte GFAP+AQP4+HOPX+                       482
Radial Glia SOX2+VIM+FABP7+                     470
Radial Glia SOX2+PAX6+FABP7+                    435
Hindbrain Neurons NR2F2+PBX3+LHX1+              256
Mesenchymal-like cells VIM+VCAN+SPARC+           78
GABAergic GAD1+GAD2+CALB2+                       36
Name: count, dtype: int64

In [7]:
dge_22q11[(dge_22q11['p.value'] < 0.05) & (dge_22q11['n.studies'] == 3)]['assay'].value_counts()

assay
Radial Glia SOX2+VIM+FABP7+                    1592
Dorsal Forebrain Neuron FOXG1+EMX1+NEUROG1+     908
Hindbrain Neurons NR2F2+PBX3+LHX1+              777
Proliferative Radial Glia SOX2+HES6+TOP2A+      605
Radial Glia SOX2+PAX6+FABP7+                    193
Mixed Neurons FGF12+GRIN2B+CAMK2B+              117
Name: count, dtype: int64

In [8]:
dge_idiopathic[(dge_idiopathic['p.value'] < 0.05) & (dge_idiopathic['n.studies'] == 2)]['assay'].value_counts()

assay
Radial Glia SOX2+PAX6+FABP7+                  437
Proliferative Radial Glia SOX2+HES6+TOP2A+    263
Radial Glia SOX2+VIM+FABP7+                    37
Hindbrain Neurons NR2F2+PBX3+LHX1+             21
Name: count, dtype: int64

In [9]:
dge_idiopathic[(dge_idiopathic['p.value'] < 0.05) & (dge_idiopathic['n.studies'] == 2)]

,ID,assay,estimate,std.error,statistic,p.value,n.studies,method,assay_ID
67,ABCB7,Radial Glia SOX2+PAX6+FABP7+,-0.656663,0.234648,-2.798498,0.005134,2,FE,Radial Glia SOX2+PAX6+FABP7+ | ABCB7
123,ABHD17B,Radial Glia SOX2+PAX6+FABP7+,-0.465031,0.231734,-2.006747,0.044777,2,FE,Radial Glia SOX2+PAX6+FABP7+ | ABHD17B
156,ABL1,Radial Glia SOX2+PAX6+FABP7+,0.579588,0.210670,2.751167,0.005938,2,FE,Radial Glia SOX2+PAX6+FABP7+ | ABL1
186,ACAA1,Radial Glia SOX2+PAX6+FABP7+,0.404988,0.204402,1.981334,0.047554,2,FE,Radial Glia SOX2+PAX6+FABP7+ | ACAA1
206,ACADM,Radial Glia SOX2+PAX6+FABP7+,-0.512016,0.224520,-2.280490,0.022579,2,FE,Radial Glia SOX2+PAX6+FABP7+ | ACADM
...,...,...,...,...,...,...,...,...,...
34546,ZNF462,Radial Glia SOX2+PAX6+FABP7+,-0.476927,0.229640,-2.076843,0.037816,2,FE,Radial Glia SOX2+PAX6+FABP7+ | ZNF462
34970,ZNF766,Radial Glia SOX2+PAX6+FABP7+,-0.612344,0.213912,-2.862593,0.004202,2,FE,Radial Glia SOX2+PAX6+FABP7+ | ZNF766
35012,ZNF787,Radial Glia SOX2+PAX6+FABP7+,0.468791,0.234346,2.000423,0.045455,2,FE,Radial Glia SOX2+PAX6+FABP7+ | ZNF787
35103,ZNF92,Radial Glia SOX2+PAX6+FABP7+,-0.556566,0.212130,-2.623706,0.008698,2,FE,Radial Glia SOX2+PAX6+FABP7+ | ZNF92
35212,ZWINT,Proliferative Radial Glia SOX2+HES6+TOP2A+,-0.437697,0.199255,-2.196670,0.028044,2,FE,Proliferative Radial Glia SOX2+HES6+TOP2A+ | Z...

In [10]:
dge_22q11[(dge_22q11['p.value'] < 0.05) & (dge_22q11['n.studies'] == 3)]

,ID,assay,estimate,std.error,statistic,p.value,n.studies,method,assay_ID
13,A1BG-AS1,Radial Glia SOX2+VIM+FABP7+,0.395336,0.108084,3.657689,0.000254,3,FE,Radial Glia SOX2+VIM+FABP7+ | A1BG-AS1
53,AAK1,Hindbrain Neurons NR2F2+PBX3+LHX1+,-0.211159,0.067742,-3.117101,0.001826,3,FE,Hindbrain Neurons NR2F2+PBX3+LHX1+ | AAK1
56,AAK1,Mixed Neurons FGF12+GRIN2B+CAMK2B+,-0.426202,0.158811,-2.683716,0.007281,3,FE,Mixed Neurons FGF12+GRIN2B+CAMK2B+ | AAK1
57,AAK1,Proliferative Radial Glia SOX2+HES6+TOP2A+,-0.201173,0.095193,-2.113320,0.034573,3,FE,Proliferative Radial Glia SOX2+HES6+TOP2A+ | AAK1
59,AAK1,Radial Glia SOX2+VIM+FABP7+,-0.442459,0.145423,-3.042564,0.002346,3,FE,Radial Glia SOX2+VIM+FABP7+ | AAK1
...,...,...,...,...,...,...,...,...,...
96717,ZSWIM6,Proliferative Radial Glia SOX2+HES6+TOP2A+,0.144518,0.061331,2.356341,0.018456,3,FE,Proliferative Radial Glia SOX2+HES6+TOP2A+ | Z...
96728,ZSWIM7,Radial Glia SOX2+PAX6+FABP7+,0.243247,0.116943,2.080041,0.037522,3,FE,Radial Glia SOX2+PAX6+FABP7+ | ZSWIM7
96729,ZSWIM7,Radial Glia SOX2+VIM+FABP7+,0.238053,0.111010,2.144436,0.031998,3,FE,Radial Glia SOX2+VIM+FABP7+ | ZSWIM7
96752,ZUP1,Radial Glia SOX2+VIM+FABP7+,-0.325663,0.162944,-1.998625,0.045649,3,FE,Radial Glia SOX2+VIM+FABP7+ | ZUP1
96757,ZW10,Proliferative Radial Glia SOX2+HES6+TOP2A+,0.303195,0.118015,2.569123,0.010196,3,FE,Proliferative Radial Glia SOX2+HES6+TOP2A+ | ZW10

In [11]:
dge_nrxn1[(dge_nrxn1['p.value'] < 0.05) & (dge_nrxn1['n.studies'] == 2)]

,ID,assay,estimate,std.error,statistic,p.value,n.studies,method,assay_ID
4,A1BG,IPC EOMES+NEUROG2+PAX6+,0.436317,0.185689,2.349718,0.018788,2,FE,IPC EOMES+NEUROG2+PAX6+ | A1BG
24,AAAS,Mixed Neurons FGF12+GRIN2B+CAMK2B+,0.194898,0.093015,2.095352,0.036140,2,FE,Mixed Neurons FGF12+GRIN2B+CAMK2B+ | AAAS
49,AAK1,Dorsal Forebrain Neuron FOXG1+EMX1+NEUROG1+,-0.250432,0.107790,-2.323336,0.020161,2,FE,Dorsal Forebrain Neuron FOXG1+EMX1+NEUROG1+ | ...
59,AAMDC,Dorsal Forebrain Neuron FOXG1+EMX1+NEUROG1+,0.367891,0.156717,2.347487,0.018901,2,FE,Dorsal Forebrain Neuron FOXG1+EMX1+NEUROG1+ | ...
68,AAMP,Dorsal Forebrain Neuron FOXG1+EMX1+NEUROG1+,0.278347,0.108563,2.563917,0.010350,2,FE,Dorsal Forebrain Neuron FOXG1+EMX1+NEUROG1+ | ...
...,...,...,...,...,...,...,...,...,...
106438,ZSCAN23,Radial Glia SOX2+VIM+FABP7+,-0.535142,0.181888,-2.942149,0.003259,2,FE,Radial Glia SOX2+VIM+FABP7+ | ZSCAN23
106517,ZSWIM5,Proliferative Radial Glia SOX2+HES6+TOP2A+,-0.427385,0.210371,-2.031578,0.042196,2,FE,Proliferative Radial Glia SOX2+HES6+TOP2A+ | Z...
106534,ZSWIM7,IPC EOMES+NEUROG2+PAX6+,0.607721,0.229183,2.651684,0.008009,2,FE,IPC EOMES+NEUROG2+PAX6+ | ZSWIM7
106540,ZSWIM8,Dorsal Forebrain Neuron FOXG1+EMX1+NEUROG1+,0.315091,0.095828,3.288070,0.001009,2,FE,Dorsal Forebrain Neuron FOXG1+EMX1+NEUROG1+ | ...
106588,ZXDB,Proliferative Radial Glia SOX2+HES6+TOP2A+,-0.330291,0.152140,-2.170970,0.029933,2,FE,Proliferative Radial Glia SOX2+HES6+TOP2A+ | ZXDB

In [25]:
## Subclass #

import glob

subclass_dge_list = []
for file_path in glob.glob('/mnt/sdb/scz_meta_analysis_processed/dge_signatures/dreamlet_dges/one_vs_all/subclass/DE_*'):
    dge = pd.read_csv(file_path, index_col=0)
    #dge = dge[(dge['adj.P.Val'] < 0.05) & (dge['logFC'] > 1)].sort_values(by='AveExpr', ascending=False)
    subclass_dge_list.append(dge)

subclass_dges = pd.concat(subclass_dge_list, axis=0)

subclass_dges = subclass_dges[~pd.Series(subclass_dges.index).str.contains('ENSG').values]

In [32]:
## Subtypes ##

subtype_dge_list = []
for file_path in glob.glob('/mnt/sdb/scz_meta_analysis_processed/dge_signatures/dreamlet_dges/one_vs_all/subtypes_remerged/DE_*'):
    dge = pd.read_csv(file_path, index_col=0)
    # dge = dge[(dge['adj.P.Val'] < 0.05) & (dge['logFC'] > 1)].sort_values(by='AveExpr', ascending=False)
    subtype_dge_list.append(dge)

subtypes_dges = pd.concat(subtype_dge_list, axis=0)

subtypes_dges = subtypes_dges[~pd.Series(subtypes_dges.index).str.contains('ENSG').values]

In [26]:
subclass_annotations_markers = {"1_1": "Radial Glia SOX2+VIM+FABP7+",
                                "1_2": "Proliferative Radial Glia SOX2+HES6+TOP2A+",
                                "1_3": "Radial Glia SOX2+PAX6+FABP7+",
                                "1_4": "Mesenchymal-like cells VIM+VCAN+SPARC+",
                                "1_5": "Stressed Glia FTL+B2M+GLUL+",
                                "2_1": "Dorsal Forebrain Neuron FOXG1+EMX1+NEUROG1+",
                                "2_2": "Hindbrain Neurons NR2F2+PBX3+LHX1+",
                                "2_3": "Mixed Neurons FGF12+GRIN2B+CAMK2B+",
                                "2_4": "GABAergic GAD1+GAD2+CALB2+"}

subclass_annotations = {"1_1": "Radial Glia",
                        "1_2": "Proliferative Radial Glia",
                        "1_3": "Radial Glia",
                        "1_4": "Mesenchymal-like cells",
                        "1_5": "Stressed Glia",
                        "2_1": "Dorsal Forebrain EN",
                        "2_2": "Hindbrain Neurons",
                        "2_3": "Mixed Neurons",
                        "2_4": "GABAergic"}

In [27]:
subclass_dges['subclass_annotated'] = subclass_dges['subclass'].map(subclass_annotations_markers)

In [28]:
subclass_dges[subclass_dges['subclass_annotated'].str.contains('Prolif')]

,logFC,AveExpr,t,P.Value,adj.P.Val,B,subclass,subclass_annotated
PIF1,5.971337,2.683721,28.437537,1.112752e-72,1.996369e-70,155.171900,1_2,Proliferative Radial Glia SOX2+HES6+TOP2A+
KIF20A,5.687146,2.565499,27.161349,1.787064e-69,2.805371e-67,147.840226,1_2,Proliferative Radial Glia SOX2+HES6+TOP2A+
DLGAP5,5.673675,4.574439,33.911766,1.714731e-85,8.613827e-83,184.672226,1_2,Proliferative Radial Glia SOX2+HES6+TOP2A+
UBE2C,5.643441,6.761425,31.094212,4.406714e-79,1.173922e-76,169.970878,1_2,Proliferative Radial Glia SOX2+HES6+TOP2A+
AURKB,5.631183,4.435484,27.646872,1.052774e-70,1.698153e-68,150.727865,1_2,Proliferative Radial Glia SOX2+HES6+TOP2A+
...,...,...,...,...,...,...,...,...
MBD6,-0.000112,4.042826,-0.001675,9.986649e-01,9.990058e-01,-7.978281,1_2,Proliferative Radial Glia SOX2+HES6+TOP2A+
SPATA13,0.000072,4.325065,0.000580,9.995375e-01,9.996877e-01,-8.008938,1_2,Proliferative Radial Glia SOX2+HES6+TOP2A+
ST6GAL1,0.000069,0.919192,0.000302,9.997594e-01,9.997594e-01,-7.522089,1_2,Proliferative Radial Glia SOX2+HES6+TOP2A+
RPL7A,-0.000059,11.742132,-0.000535,9.995740e-01,9.996877e-01,-7.955349,1_2,Proliferative Radial Glia SOX2+HES6+TOP2A+
CISD1,0.000040,6.361537,0.000462,9.996316e-01,9.996884e-01,-8.135627,1_2,Proliferative Radial Glia SOX2+HES6+TOP2A+

In [40]:
subclass_dges[subclass_dges.index.str.contains('FOXG1$')].sort_values(by='t')

,logFC,AveExpr,t,P.Value,adj.P.Val,B,subclass,subclass_annotated
FOXG1,-2.942153,3.262970,-3.904292,0.000133,0.000427,-0.035319,1_4,Mesenchymal-like cells VIM+VCAN+SPARC+
FOXG1,-2.102609,4.467173,-3.437384,0.000714,0.004682,-1.238121,2_2,Hindbrain Neurons NR2F2+PBX3+LHX1+
FOXG1,-0.795420,3.570622,-1.268158,0.206196,0.278948,-7.193221,1_1,Radial Glia SOX2+VIM+FABP7+
FOXG1,-0.236362,4.804510,-0.346865,0.729075,0.816776,-6.829824,2_3,Mixed Neurons FGF12+GRIN2B+CAMK2B+
FOXG1,-0.645244,3.694952,-0.217925,0.827882,0.864339,-6.672628,1_5,Stressed Glia FTL+B2M+GLUL+
FOXG1,0.072715,3.834986,0.111407,0.911404,0.935835,-7.957791,1_2,Proliferative Radial Glia SOX2+HES6+TOP2A+
FOXG1,1.245452,4.019967,1.944931,0.053188,0.130654,-5.600706,1_3,Radial Glia SOX2+PAX6+FABP7+
FOXG1,1.263211,4.852173,2.190531,0.029636,0.100580,-4.621415,2_1,Dorsal Forebrain Neuron FOXG1+EMX1+NEUROG1+
FOXG1,2.906834,5.489112,4.623391,0.000007,0.000064,2.867936,2_4,GABAergic GAD1+GAD2+CALB2+

In [38]:
subtypes_dges[subtypes_dges.index.str.contains('FOXG1') & subtypes_dges['subtype'].str.contains('^2_4')].sort_values(by='t')

          logFC   AveExpr         t   P.Value  adj.P.Val         B subtype
FOXG1 -0.858212  7.716787 -3.702390  0.000263   0.000924 -0.471124   2_4_4
FOXG1  0.400519  7.802891  1.744835  0.082177   0.149608 -5.537458   2_4_3
FOXG1  0.714629  7.863325  3.661592  0.000300   0.003530 -0.215603   2_4_1
FOXG1  0.800944  7.845756  4.029654  0.000072   0.000262  0.621969   2_4_2

In [33]:
subtypes_dges

,logFC,AveExpr,t,P.Value,adj.P.Val,B,subtype
RSPO3,4.681064,3.695293,17.284870,4.348826e-52,3.896838e-49,107.704452,1_1_1
TRH,4.004972,3.879069,14.108177,6.850742e-38,1.315440e-35,75.306249,1_1_1
TTR,3.659109,3.856470,9.863749,5.710184e-21,1.262345e-19,36.762108,1_1_1
RSPO2,3.531995,3.422322,15.360960,2.204278e-43,8.007488e-41,87.836469,1_1_1
RASSF9,3.527491,2.208304,17.773582,2.448252e-54,2.742246e-51,112.762912,1_1_1
...,...,...,...,...,...,...,...
PCDHB15,-0.000109,3.486460,-0.000822,9.993443e-01,9.996616e-01,-6.750071,2_3_1
POLD1,0.000089,2.208296,0.000614,9.995107e-01,9.996699e-01,-6.570676,2_3_1
TEX261,-0.000063,3.473005,-0.000724,9.994228e-01,9.996616e-01,-6.745119,2_3_1
TMEM167A,-0.000017,7.231755,-0.000313,9.997504e-01,9.997972e-01,-6.931525,2_3_1
LTA4H,0.000015,4.750901,0.000254,9.997972e-01,9.997972e-01,-6.836231,2_3_1